### ISSUE TITLE
Font and option suggestion

### ISSUE THREAD

**Issue by Mara-Li** [FlorianWoelki/obsidian-icon-folder#1]
Hello.
I work since Day on my css snippet for icon. I want to know if it's possible to fusion with your plugin. 

So, some suggestion : 
- Font
	- Font Awesome (Regular, Brands, and Solid)
	- Boxicons
	- IconMoons Free
	- Material Icons
- Adding an option to change size (because you use remixicons 16px) with Style settings
- Adding an option to change placement settings (padding, margin, vertical-align and maybe left) 
- Adding an option to change color

I think, if we can, fusion my snippet and your plugin can be super cool for other user !

**Comment by brimwats** [comment]
Also, if possible, Material Design Icons: https://materialdesignicons.com

**Comment by DutchPete** [comment]
Cute, and very easy to use! Many thanks.
Hopefully, whatever you do in terms of improvement/tweaks/alteration, ease of use will remain the principle.

**Comment by FlorianWoelki** [comment]
> Hello.
> I work since Day on my css snippet for icon. I want to know if it's possible to fusion with your plugin.
> 
> So, some suggestion :
> 
> * Font
>   
>   * Font Awesome (Regular, Brands, and Solid)
>   * Boxicons
>   * IconMoons Free
>   * Material Icons
> * Adding an option to change size (because you use remixicons 16px) with Style settings
> * Adding an option to change placement settings (padding, margin, vertical-align and maybe left)
> * Adding an option to change color
> 
> I think, if we can, fusion my snippet and your plugin can be super cool for other user !

I would love to collaborate and I really like your ideas!

You can feel free to add a PR and I will add you as a collaborator to this plugin :)

> Also, if possible, Material Design Icons: https://materialdesignicons.com

Sure! Just open up another issue for that. I've created a [project roadmap](https://github.com/FlorianWoelki/obsidian-icon-folder/projects/1), so we can keep track of the current tasks, issues, and their progress.

> Cute, and very easy to use! Many thanks.
> Hopefully, whatever you do in terms of improvement/tweaks/alteration, ease of use will remain the principle.

Thank you for the kind feedback! User experience and simplicity will be priority number one!

**Comment by Mara-Li** [comment]
I don't know Typescript, but you can found my snippet here : https://github.com/Mara-Li/Obsidian-Snippet-collection/blob/main/folders.icon.css

Don't worry about take it to work / tweak with it!

**Comment by FlorianWoelki** [comment]
> I don't know Typescript, but you can found my snippet here : https://github.com/Mara-Li/Obsidian-Snippet-collection/blob/main/folders.icon.css
> 
> Don't worry about take it to work / tweak with it!

Sure, thanks :) I will keep this issue open to notify you when it is done. In addition, I will create [another issue](https://github.com/FlorianWoelki/obsidian-icon-folder/issues/3) for customizing the size, color, and placement.

**Comment by Mara-Li** [comment]
Any update on this ?

**Comment by FlorianWoelki** [comment]
Not yet. But I will try to think today of an idea to easily customize the icons.

**Comment by Mara-Li** [comment]
Thank ! I check, and, with CSS I do something with change width and height : 
```css
.obsidian-icon-folder-icon > svg {
    width: var(--size);
    height: var(--size);
    left: var(--left-align);
    top: var(--vertical-align);
    position: relative;
}
```
Using Style Settings permit to custom size, left and vertical align.

So, the idea is to add this but for all icon ? In the same place you store the other data ? 
I don't know if it's possible to add dynamic option but if yes :  Each time a new icon is added → add option in settings. 
If no... A command, maybe ? With a modal to choose the folder/file ? 
I'm don't like to add menu because I have a lot of option so it can be a pain to have again option. But I think it's the only viable solution.

**Comment by FlorianWoelki** [comment]
Yeah. I like the idea of changing the style of all icons. For style changes for a single item might be too much.

**Comment by FlorianWoelki** [comment]
Hey there.

You can now checkout the code and test the customizations for yourself! @Mara-Li would be good if you can give some feedback, if the current customization options fit your needs (font size and color)

**Comment by Mara-Li** [comment]
Yeah I will check that !

**Comment by Mara-Li** [comment]
It seems that changing the size doesn't do anything. Color work as expected.

**Comment by FlorianWoelki** [comment]
Hm interesting. For me, it's working fine.

**Comment by Mara-Li** [comment]
Ah, I forgot to remove my css ! 
It work as intended so 👍 

It can be very good to add a way to change position/size for specific icon.

**Comment by FlorianWoelki** [comment]
Beautiful!

I will think about it. The problem is that the data can be really huge the more folders and icons you have. I try to keep it as lean and clean as possible.

**Comment by Mara-Li** [comment]
Yeah, I completely understand!

**Comment by FlorianWoelki** [comment]
I've added the ability to change the padding of the icon. Therefore #3 is closed and therefore some parts of this issue. Should we create an extra issue for the icon packs?

**Comment by Mara-Li** [comment]
No, I think it's okay o/ Thank you !
