### ISSUE TITLE
[Feature Request] Allow same icon for all folders and files of those without an icon

### ISSUE THREAD

**Issue by Obadiahcruz** [FlorianWoelki/obsidian-icon-folder#10]
1. Please allow to change all icons with the same icon. 
2. Allow all remaining files without an icon to have same icon change. 
3. allow files to have all same icon feature separate from folders. 

This would be a great update !

**Comment by FlorianWoelki** [comment]
Issue is implemented with [release 1.0.4](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.0.4)
