### ISSUE TITLE
Icon Brew does not add due to _MAC_OSX *non-*hidden directory on Windows

### ISSUE THREAD

**Issue by namtrah** [FlorianWoelki/obsidian-icon-folder#100]
**Describe the bug**
Tried to add the new "Icon Brew" icon Pack

**To Reproduce**
Just press "Browse Icon Packs and select the Icon Brew pack.

**Expected behavior**
They should load.

**Screenshots**
**Additional context**
![image](https://user-images.githubusercontent.com/13903735/180652609-46c626af-a876-4cf7-b419-9877e1ed6af1.png)

**Comment by FlorianWoelki** [comment]
Should be fixed with [version 1.3.3](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.3.3).
