### ISSUE TITLE
The main icon color overrides the colors specified in the custom icon rules after the client restarts

### ISSUE THREAD

**Issue by Fertion** [FlorianWoelki/obsidian-icon-folder#102]
**Describe the bug**
The main icon color overrides the colors specified in the custom icon rules after the client restarts.

**To Reproduce**
1) I set the rules - the colors are displayed correctly
2) Reloading the obsidian - all icons have the same color, even those for which a different color is set in the rules
3) If I choose a color again - it is displayed correctly until the next restart

**Expected behavior**
The rules must continue to work after a restart

**Screenshots**
![image](https://user-images.githubusercontent.com/102726751/181112598-99c5d2f9-8495-4eb8-a85b-ae85b737c8c9.png)
![image](https://user-images.githubusercontent.com/102726751/181112659-14e13635-04d1-4472-b349-2c4c6e64831b.png)
![image](https://user-images.githubusercontent.com/102726751/181112731-710f2e4f-375e-402d-9af9-0449dc8a7a2d.png)

**Comment by Fertion** [comment]
I am using version 1.3.31

**Comment by FlorianWoelki** [comment]
Should now be fully functional in release [1.3.4](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.3.4).
