### ISSUE TITLE
Add icons to starred notes

### ISSUE THREAD

**Issue by FlorianWoelki** [FlorianWoelki/obsidian-icon-folder#103]
![image](https://user-images.githubusercontent.com/12601762/156950373-8a08889b-2d83-40b5-84f7-aca6f0676f61.png)

https://help.obsidian.md/Plugins/Starred+notes

So you have a file with an icon...
![image](https://user-images.githubusercontent.com/12601762/156950440-9b0716e4-0585-459c-8676-1671d523a284.png)

But then in the starred section...
![image](https://user-images.githubusercontent.com/12601762/156950467-3f7f6541-3966-4622-b002-75071f6c9758.png)

_Originally posted by @Mobuos in https://github.com/FlorianWoelki/obsidian-icon-folder/issues/40#issuecomment-1060084468_

**Comment by FlorianWoelki** [comment]
Should now be fully functional in release [1.3.4](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.3.4).

**Comment by Lisandra-dev** [comment]
I can successfully use the icons in the star plugins :  
![image](https://user-images.githubusercontent.com/30244939/188268964-7e99c851-8da8-46e2-bb1c-bc01702674a9.png)
I have this error when I activate/deactivate the star plugin.
