### ISSUE TITLE
Custom rule set to Folder type applies to both folder and any nested files

### ISSUE THREAD

**Issue by PragmaticallyWhimsical** [FlorianWoelki/obsidian-icon-folder#105]
**Describe the bug**
Create a custom rule that targets a folder. Any files under that folder will also receive the icon.

**To Reproduce**
1. Create a folder, with a file inside of it
2. Create a custom rule that targets the folder
3. Ensure the custom rule is set to the Folder Type (to trigger this behavior, you need to cycle through the types).
4. The folder will receive the icon as intended, but the nested files will also receive the icon (not intended).
5. A restart resolves this (until you try changing the type again), but would rather not have to restart my vault every time a new icon is added for a folder.

**Expected behavior**
If I create a custom rule targeting folders, it should only apply to folders. Not every file nested beneath the folder as well.

**Screenshots**
Unintended Behavior:
![image](https://user-images.githubusercontent.com/90495689/182401341-7e6a6933-8b32-4040-9183-6ce057ee4662.png)

Custom Rule:
![image](https://user-images.githubusercontent.com/90495689/182401444-5ef24561-507f-44dd-8a5d-e0573d8f80ac.png)

**Additional context**
This used to work in a previous version as in my main vault I use version 1.2.1 as later versions break other things for me still ( some of which I see are being fixed/worked on :) ).

**Comment by FlorianWoelki** [comment]
In theory, this should not even apply to a file because you have set the rule to `^Templates`. Therefore it should only match the directory, when selected. I've fixed that in the recent commit.

**Comment by PragmaticallyWhimsical** [comment]
Awesome, thanks! I'll be sure to check it out :).

**Comment by FlorianWoelki** [comment]
Should now be fully functional in release [1.3.4](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.3.4).

**Comment by PragmaticallyWhimsical** [comment]
Hey, Sorry for the delay on this @FlorianWoelki, I was able to check today and looks like your fix solved the issue I was seeing. Thanks, I appreciate it!
