### ISSUE TITLE
Icons show the same

### ISSUE THREAD

**Issue by RustedAperture** [FlorianWoelki/obsidian-icon-folder#106]
**Describe the bug**
Icons that appear in multiple packs will only show one version

**To Reproduce**
1. Install both fontawesome regular and solid.
2. change icon on folder
3. search for moon
4. both FAR and FAS show same icon

**Expected behavior**
one should be solid and the other should be outline

**Screenshots**
![image](https://user-images.githubusercontent.com/6724171/183235817-6f4ff3c1-1f1e-447f-ae25-4b79136d0971.png)

**Additional context**
This also applies to the file explorer.  will display incorrect icon until you close and open the obsidian.

**Comment by FlorianWoelki** [comment]
Should now be fully functional in release [1.3.4](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.3.4).
