### ISSUE TITLE
Tabler Icons not showing correctly

### ISSUE THREAD

**Issue by ShahriarKh** [FlorianWoelki/obsidian-icon-folder#107]
I downloaded tabler icons (https://github.com/tabler/tabler-icons/releases/download/v1.78.1/tabler-icons-1.78.1.zip), unzipped it, and put the "icons" folder (where SVG icons are located) in the plugin folder (`.obsidian/plugins/obsidian-icon-folder/icons/`). The settings work fine and all 2160 icons are detected, but they don't show up correctly:
![image](https://user-images.githubusercontent.com/31452340/183255026-4073840b-7219-426c-9e3a-ef778493e7a9.png)
I tried changing the theme to default one, but no luck 😕
What could be the problem?

**Comment by ShahriarKh** [comment]
I found the problem: some attributes are being deleted:
For example, `bell.svg`:
### Actual Icon SVG
```html
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-bell" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6" />
  <path d="M9 17v1a3 3 0 0 0 6 0v-1" />
</svg>
```

### Obsidian Output
```html
<svg width="24px" fill="none" height="24px" viewBox="0 0 24 24">
    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
    <path d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6"></path>
    <path d="M9 17v1a3 3 0 0 0 6 0v-1"></path>
</svg>
```
Seems like all attributes starting with `stroke-` are being deleted. (`class` and `xmlns` aren't important here, so no problem)

**Comment by ShahriarKh** [comment]
[  if (foundIcon) {
    let fileContent: string;
    if (typeof foundIcon.svgPath === 'object') {
      const doesStrokeExists = foundIcon.svgPath.filter((path: any) => path.match(/stroke=".*"/g)).length !== 0;
      fileContent = `<svg width="16" ${doesStrokeExists ? 'fill="none"' : 'fill="currentColor"'} height="16" ${
        foundIcon.svgViewbox.length !== 0 ? foundIcon.svgViewbox : 'viewbox="0 0 24 24"'
      }>${foundIcon.svgContent}</svg>`;
    } else {
      fileContent = `<svg width="16" height="16" ${foundIcon.svgPath.includes('fill=') ? '' : 'fill="currentColor"'} ${
        foundIcon.svgViewbox.length !== 0 ? foundIcon.svgViewbox : 'viewbox="0 0 24 24"'
      }>${foundIcon.svgContent}</svg>`;
    }
    icon = fileContent;
  }


  return icon;
};](https://github.com/FlorianWoelki/obsidian-icon-folder/blob/f3915a626f80349fbcb91acde1a2d2c5750b625a/src/iconPackManager.ts#L368-L384)

**Comment by FlorianWoelki** [comment]
I'll take a look at it as soon as I have the time. Thank you for the detailed analysis!

**Comment by FlorianWoelki** [comment]
This is fixed in the [newest release](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.5.0). Thanks for reporting!
