### ISSUE TITLE
Use margin instead of padding

### ISSUE THREAD

**Issue by ShahriarKh** [FlorianWoelki/obsidian-icon-folder#108]
Not all themes and icon packs work well together, and setting icon padding is a great thing in options. However, it currently doesn't allow negative values. I suggest to switch from `padding` to `margin` so negative values are accepted.

### ✔ With margin:
`margin: 0 -7px 0 2px;`

![image](https://user-images.githubusercontent.com/31452340/183255374-d63f14ac-373e-4754-9301-4995499be227.png)

### ❌ With padding:
`padding: 0 0 0 2px`

![image](https://user-images.githubusercontent.com/31452340/183255398-d5555e36-316f-4ade-acc6-dff154ae57e2.png)

**Comment by FlorianWoelki** [comment]
Fixed with #109.

**Comment by ShahriarKh** [comment]
Today I noticed that we replaced padding with margin, but the slider in plugin options starts from 0 and doesn't support negative values! Please re-open the issue.

**Comment by FlorianWoelki** [comment]
Thanks for reporting! It should be fixed with the next release.
