### ISSUE TITLE
RPG-Awesome icons not rendering in Obsidian File Explorer

### ISSUE THREAD

**Issue by rokville** [FlorianWoelki/obsidian-icon-folder#110]
The icon pack was downloaded from here: [https://nagoshiashumari.github.io/Rpg-Awesome/](https://nagoshiashumari.github.io/Rpg-Awesome/)

The icon pack appears to be loaded correctly according to the Icon Folder Options
![Screen Shot 2022-08-08 at 11 56 45 AM](https://user-images.githubusercontent.com/107450392/183472404-8086f2f0-4cb6-4c21-b879-f2e83196aba8.png)

Icons appear as expected in the Icon Folder Chooser
selected Capitol
![Screen Shot 2022-08-08 at 11 59 07 AM](https://user-images.githubusercontent.com/107450392/183472417-ba59775d-a8e4-4c6a-a62d-839d53110cb1.png)

But the filename displays rather than the icon.
![Screen Shot 2022-08-08 at 12 01 41 PM](https://user-images.githubusercontent.com/107450392/183472432-cd016ff4-0c5c-4da7-b91b-45f3891629c2.png)

-- Update with additional Info
After an unrelated re-load of Obsidian, I noticed this notice in my opening load
![Screen Shot 2022-08-08 at 1 49 05 PM](https://user-images.githubusercontent.com/107450392/183481410-a8eef163-17e3-4643-b5f2-d2339c0cf08b.png)

and the debugger console lists this:
![Screen Shot 2022-08-08 at 1 50 51 PM](https://user-images.githubusercontent.com/107450392/183481642-eabba6a0-aa8a-4a5f-938e-30b5b0d01006.png)

**Comment by FlorianWoelki** [comment]
Should be fixed in [1.6.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.6.0).

**Comment by rokville** [comment]
Looks good, thank you!!
