### ISSUE TITLE
Custom Icons with dash in filename doesn't work correctly

### ISSUE THREAD

**Issue by ShahriarKh** [FlorianWoelki/obsidian-icon-folder#111]
Tabler icons are named with dashes, like this: `access-point-off.svg`. However, the plugin renames the icon to something like `TaAccessPointOff`, so when I reopen the app, the icon can't show up. If I rename the file and remove dashes (like `accesspointoff.svg`) then it works like before.

#### Before closing:
![image](https://user-images.githubusercontent.com/31452340/187679799-3e6c0b75-d6da-47ea-8895-766f6305b87b.png)
#### When I re-open Obsidian:
![image](https://user-images.githubusercontent.com/31452340/187679834-94803936-8d02-458b-b7f7-775b1cec48e3.png)

I noticed this doesn't happen to icons with single names, like `bell.svg`

**Comment by FlorianWoelki** [comment]
Should be fixed in [1.6.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.6.0).
