### ISSUE TITLE
Icon Picker Does not Allow you To Scroll Through Entire Icon Pack

### ISSUE THREAD

**Issue by davenukem** [FlorianWoelki/obsidian-icon-folder#113]
It appears there's a limitation with how many icons are displayed when you select the option to change a folder icon? Is this an inbuilt limitation? 

I can utilize search to find the icons, but am unable to scroll through all of them.

**Comment by FlorianWoelki** [comment]
Yes this is a built in limitation to have good performance for the icon picker.
