### ISSUE TITLE
Twemoji icon missing in "Drag to rearrange"

### ISSUE THREAD

**Issue by Zheoni** [FlorianWoelki/obsidian-icon-folder#115]
**Describe the bug**
When a twemoji is set as the icon of a note, it is not visible in the rearrange icon of the editor. It does remove the default icon.

**To Reproduce**
1. Create a note.
2. Set (any) twemoji as its icon.
3. Open the file to see the missing icon.

**Expected behavior**
I expect to see the twemoji as the drag icon. It is a bug as the default "file" icon is removed.

**Screenshots**
Current behaviour.
![Captura de pantalla 2022-09-12 182106](https://user-images.githubusercontent.com/38019254/189705844-12e86284-475e-469c-8f36-a3c395b009d2.png)

Expected behaviour.
![Captura de pantalla 2022-09-12 182217](https://user-images.githubusercontent.com/38019254/189705909-454f757e-5716-4f0b-9078-3ea6379362f8.png)

**Additional context**
The problem is here:
https://github.com/FlorianWoelki/obsidian-icon-folder/blob/a1541addf18954f9735281286a2a5e9b01b7d598/src/util.ts#L266-L269

When the icon is a twemoji the function returns an empty string and the icon is completely removed. I have already implemented a quick solution shown in the expected behaviour screenshot. Maybe is not the best one but works. If you are comfortable with me submitting a pull request let me know 😄.

**Comment by FlorianWoelki** [comment]
Thanks for reporting!

Feel free to open a Pull Request for that :)
