### ISSUE TITLE
non-aligned icons after upgrade to obsidian 1.0

### ISSUE THREAD

**Issue by aliamini87** [FlorianWoelki/obsidian-icon-folder#120]
Although I modified alignment setting as far as I could, it seems that icons position relative to text is not correct.

![image](https://user-images.githubusercontent.com/91720545/195827449-1101664a-3fc2-46a3-ab89-3422c736e45c.png)

**Comment by rockmanvnx6** [comment]
having the same issue. I thought it was conflict of other plugins but this plugin is the issue

**Comment by FlorianWoelki** [comment]
This issue should now be fixed with version [1.3.5](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.3.5).
