### ISSUE TITLE
Show Twemoji in Icon Search 

### ISSUE THREAD

**Issue by paperdave** [FlorianWoelki/obsidian-icon-folder#123]
**Is your feature request related to a problem? Please describe.**
Some linux installs do not have an emoji picker built in.

**Describe the solution you'd like**
Listing all the twemoji icons in the icon search list. This would also make the icon search feel nicer if there weren't any icon packs installed as there wouldn't be an empty list.

**Describe alternatives you've considered**
i've considered dealing with it. i installed the emoji picker app "emote" which does the job but not as nice as having the integrated icon search would be.

**Comment by FlorianWoelki** [comment]
Thanks for the report!

A fix has already been made. The release will be live on a couple of days.
