### ISSUE TITLE
Outdated Twemoji version

### ISSUE THREAD

**Issue by Ellpeck** [FlorianWoelki/obsidian-icon-folder#125]
**Describe the bug**
I'm not sure this necessarily counts as a *bug*, but while taking some notes on coffee, I noticed that the [beans emoji](https://emojipedia.org/beans/) is not available in the Twemoji version you're using yet, causing it to look less than ideal (since it now simply displays the Windows version of the emoji as text, rather than the Twemoji svg). As you can see, [Twemoji 14](https://github.com/twitter/twemoji/releases/tag/v14.0.0) seems to have added this emoji, and quite a few more. Would it be possible for the Twemoji version used to be updated?

Thanks so much!

**To Reproduce**
1. Use an icon not present in older Twemoji versions, like 🫘
2. That's it, the icon will now be the OS's version, meaning it displays as a text paragraph that won't scale properly according to the plugin's icon size settings.

**Comment by FlorianWoelki** [comment]
Thanks for the report. This issue is fixed with the latest commit. A release will be in the next weeks!
