### ISSUE TITLE
Emojis don't show up in search results when no icon pack is selected

### ISSUE THREAD

**Issue by ShahriarKh** [FlorianWoelki/obsidian-icon-folder#126]
With the recent update, inseting emojis is lot easier! However, when you have no icon packs selected, emojis don't show up in search results.

1. Click on "change icon" when no icon packs are installed.
2. Search for an emoji name, like "zombie".
3. The "You need to create an icon pack" message appears instead.

Without any icon packs:
![image](https://user-images.githubusercontent.com/31452340/201519074-38ffbf40-0443-4d1a-9256-b4aa4e5a8d2a.png)

With "Simple icons" enabled (for example):
![image](https://user-images.githubusercontent.com/31452340/201519114-4fad031c-9262-44f0-b328-a303a0e543c9.png)

I need to say that just typing the full name of the emoji or inputting an emoji directly via OS's native emoji picker, then hitting <kbd>Enter</kbd> correctly sets the emoji as the icon of the folder in both scenarios.

**Comment by FlorianWoelki** [comment]
Good catch! Thanks for reporting. It should be fixed with the next release.
