### ISSUE TITLE
[Feature Request] Unbind default color

### ISSUE THREAD

**Issue by josephdong1000** [FlorianWoelki/obsidian-icon-folder#127]
Just to preface this, I've been using the plugin for a really long time now, and I very much love the plugin!

With the new update that adds an icon color picker though, it overrides the default color used for folder icons. This might be good in some cases, but I regularly switch themes and it's a headache to go to Settings just to change the default color. I also use themes that color folder names differently, which visually clashes with the single constant color used for all of my folder icons.

It would be nice to have a toggle to turn off this feature so that the icons can be colored per their default settings.

_Screenshots for what I mean (new on left, old on right):_

<p float="left">
  <img src="https://user-images.githubusercontent.com/84431899/201539052-8429194f-4a8b-4d5a-a404-d108179674ea.png" height="500" />
  <img src="https://user-images.githubusercontent.com/84431899/201539239-cc103764-bc69-40f0-af57-c3eea5d5eda6.png" height="500" /> 
</p>

**Comment by FlorianWoelki** [comment]
Thanks for reporting! This was actually not intended and shouldn't be black at all. It should be fixed within the new release.

**Comment by josephdong1000** [comment]
The update fixed the issue! But if I change the color to something else and then click on Default, I need to restart Obsidian before the changes take into effect.

**Comment by FlorianWoelki** [comment]
Thanks for reporting again! Should be fixed in the next release.
