### ISSUE TITLE
My icons fill themselves

### ISSUE THREAD

**Issue by juanchiparra** [FlorianWoelki/obsidian-icon-folder#131]
Hey! Today I downloaded the Lucide icons (https://lucide.dev/) for use with Icon Folders. Although I downloaded the icons without being filled with color, when I add them to Obsidian they appear filled. I checked the theme I have installed and I shouldn't have to modify the icons. There is also no custom setting in my CSS code that should do this, what could be happening, is there a way to fix it with CSS?

![Screenshot 2022-11-25 151428](https://user-images.githubusercontent.com/56851264/204053830-068ac630-bfa0-4e89-9676-3d1a9803eb50.png)

![Screenshot 2022-11-25 151448](https://user-images.githubusercontent.com/56851264/204053841-bb823230-b03e-4de8-9f3e-6b49b7f5a713.png)

**Comment by FlorianWoelki** [comment]
Thank you for reporting. The issue should be fixed in the new release!

**Comment by juanchiparra** [comment]
Wow, that was fast. It's working now, thanks
