### ISSUE TITLE
Plugin Deleting Entire Vault / Other Files inside.

### ISSUE THREAD

**Issue by MrMysterius** [FlorianWoelki/obsidian-icon-folder#132]
### What happened? (Bug Description)

I wanted to change the `Icon Packs folder path` since I have from another plugin `Icon Shortcodes` already packs/icons downloaded.
![image](https://user-images.githubusercontent.com/25854814/204057177-a540201e-18f6-4d67-a6c9-49ec07fa1a84.png)

But when you enter a different folder and click `Save` then the folder it was set to before will be deleted. The same goes for Vault root or the `.obsidian`-Folder itself. This deleted my whole Vault. (Luckily Backed UP)

### To Reproduce
1. Go to `Icon Folder`'s Settings
2. Change `Icon Packs folder path` so it is empty (basically root)
3. Click `Save`
4. Change `Icon Packs folder path` again to something random like `abcdef`
5. Click `Save`
6. Root Folder aka the Vault is now deleted.

### Expected behavior
Expected behavior should be that the old folder is not deleted. That should be obvious by now. Probably something about detecting if other files are present and not deleting then (or just no deleting in general).

### Probably the Problematic Lines of Code

https://github.com/FlorianWoelki/obsidian-icon-folder/blob/b7afc265479f046ee56819291fb1e48fade333d9/src/settingsTab/iconPacksPath.ts#L32

https://github.com/FlorianWoelki/obsidian-icon-folder/blob/a1c6499a4e39feb1474d46dbc52e22ec04472840/src/iconPackManager.ts#L37-L64

https://github.com/FlorianWoelki/obsidian-icon-folder/blob/a1c6499a4e39feb1474d46dbc52e22ec04472840/src/iconPackManager.ts#L62

**Comment by MrMysterius** [comment]
If you do not intend on fixing/changing this, at least warn the user that this can happen!

**Comment by FlorianWoelki** [comment]
Thank for reporting this important issue!
The issue will be resolved in the next release.
