### ISSUE TITLE
Broken Icon Sizes

### ISSUE THREAD

**Issue by Canelparne** [FlorianWoelki/obsidian-icon-folder#134]
**Describe the bug**
Newest update broke the icons' sizes. They became huge, some of them.

**To Reproduce**
1. Update the plugin from 1.4.1 (I assume) to 1.4.2-3 (Both released 4 days, so I'm not sure anymore)
2. The size of some icons would change from native to gigantic (Some remained okay)

**Expected behavior**
If you update the plugin to the latest version, it breaks it and changes the icons' size, becoming abnormal

**Screenshots**
https://i.imgur.com/gUwnK3o.png
https://i.imgur.com/nrk8YMz.png

**Additional context**
I tried reinstalling the plugin, readding the icons and whatnot, but they remain big

**Comment by FlorianWoelki** [comment]
Hi there!

Could you please send me an example SVG where the custom icon size does not work?

**Comment by Canelparne** [comment]
![female-vampire](https://user-images.githubusercontent.com/97625901/205617111-6107c15c-5ce4-46f1-abff-441572c1a36f.svg)

**Comment by FlorianWoelki** [comment]
This is fixed in the [newest release](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.5.0). Thanks for reporting!
