### ISSUE TITLE
Vim logo doesn't have color

### ISSUE THREAD

**Issue by ilongshan** [FlorianWoelki/obsidian-icon-folder#135]
**Describe the bug**
I download vim logo from wiki (https://upload.wikimedia.org/wikipedia/commons/9/9f/Vimlogo.svg), but it doesn't have color.
<img width="152" alt="image" src="https://user-images.githubusercontent.com/7447401/206826839-90f5675e-f708-4988-8b51-4db169514186.png">

**To Reproduce**
1. download vim logo from https://upload.wikimedia.org/wikipedia/commons/9/9f/Vimlogo.svg
2. add it as a custom icon pack
3. use it as the folder color

**Expected behavior**
Expect it show the color of the image

**Screenshots**
<img width="152" alt="image" src="https://user-images.githubusercontent.com/7447401/206826854-e48de526-6183-45cb-b495-3477e782954a.png">

**Comment by FlorianWoelki** [comment]
This is fixed in the [newest release](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.5.0). Thanks for reporting!
