### ISSUE TITLE
Try to fix icon pack, only a small subset of icons shows up

### ISSUE THREAD

**Issue by arminus** [FlorianWoelki/obsidian-icon-folder#136]
**Describe the bug**
When trying to set an icon, I only the a limited part of the icon packs I have installed (can't scroll down any further):

![IconList](https://user-images.githubusercontent.com/683680/207064908-b2010a17-3cf2-4ec4-b42d-b57e28927c5e.png)

All the icon packs I have installed (since some months) show up with a "Try to fix button", clicking it doesn't appear to fix whatever might be broken:

![FixIcons](https://user-images.githubusercontent.com/683680/207065040-13f203ef-74f3-41cd-acae-37db5cb81218.png)

**To Reproduce**
1. Obsidian v1.0.3 on Win10, IconFolder 1.4.3
2. Icon packs downloaded to the vault's /.obsidian/obsidian-icon-folder/icons folder, as set in the preferences

**Expected behavior**
All icons to show up (this did work up to a certain point in the past)

**Screenshots**
See above

**Comment by FlorianWoelki** [comment]
This is not an issue. Because loading all icons does take a lot of time, it's only possible at the moment to load a specific amount of icons smoothly. You just need to search for something you want as an icon. This won't be fixed because obsidian does not allow currently to have lazy loaded modals.
