### ISSUE TITLE
Name of icon shows instead of actual icon

### ISSUE THREAD

**Issue by valevasqc** [FlorianWoelki/obsidian-icon-folder#138]
**Describe the bug**
Whenever I reload my vault, the icons disappear and are replaced by their name (for example, the icon will show "FasGraduationCap" instead of the actual icon).

**Expected behavior**
I expect to see the icon, not the name.

**Comment by FlorianWoelki** [comment]
I cannot reproduce this issue. For me this specific icon works fine.
