### ISSUE TITLE
Add option to disable twemojis

### ISSUE THREAD

**Issue by wheeleran** [FlorianWoelki/obsidian-icon-folder#139]
hi. am relatively new to Obsidian, latest version, Minimal Theme, working with the Icon Folder plugin, custom path set to .obsidian/icons, installed only the remix-icons pack. BUT i'm getting all these colorful Twemoji icons in folder icon search results. they're cute, but i don;t want them, didn't install them, and would like them gone but can't find them to delete them. the only other plugins i've got installed are dataview, highlightr, kanban, style settings, and paste URL into selection.... can someone advise?

**Comment by FlorianWoelki** [comment]
Thanks for reporting.
Currently, the twemojis are embedded by default. I am going to search for a solution to disable them.

**Comment by wheeleran** [comment]
Much appreciated!

**Comment by wheeleran** [comment]
hi @FlorianWoelki happy new year! any chance of being able to disable, remove, or delete them manually while waiting for an update to this request?

**Comment by wheeleran** [comment]
hi @FlorianWoelki Happy New Year. just as a stupid little hack while waiting/hoping for this, i deleted #314-2172 from main.js. seems to do the job; do you see any issues with doing that?

**Comment by FlorianWoelki** [comment]
Should be available in [1.6.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.6.0).

**Comment by wheeleran** [comment]
@FlorianWoelki great, thanks, much appreciated, one question (i suppose obvious): what's the difference between 'none' and 'native.' i don't see any difference; both disable twemojis, but other than that.... ?

**Comment by FlorianWoelki** [comment]
Native enables native emojis. It depends on which operating system you use.

**Comment by wheeleran** [comment]
Got it, thanks!! Any chance a future update might add a simple :hover state color? It's easy enough with a snippet, but would be a nice little addition.

**Comment by FlorianWoelki** [comment]
> Got it, thanks!! Any chance a future update might add a simple :hover state color? It's easy enough with a snippet, but would be a nice little addition. 

Do you mean with a hover effect a tooltip or some description what's the purpose of this option is?

**Comment by wheeleran** [comment]
Not at all. I'm using Minimal dark theme, with sidebar font color #999 and #ddd on hover, so I added a snippet .nav-folder-title:hover > div.obsidian-icon-folder-icon > svg { fill:#ddd !important } to match that. Make sense?

**Comment by FlorianWoelki** [comment]
> Not at all. I'm using Minimal dark theme, with sidebar font color #999 and #ddd on hover, so I added a snippet .nav-folder-title:hover > div.obsidian-icon-folder-icon > svg { fill:#ddd !important } to match that. Make sense?

Ok got it. Will add this as well yeah.
