### ISSUE TITLE
[bug] Icon on file removed on vault reload

### ISSUE THREAD

**Issue by Mara-Li** [FlorianWoelki/obsidian-icon-folder#14]
My icon added on file are removed when I reload Obsidian. It is possible to update to fix this ? It will be so cool to have this plugin work with file !

**Comment by FlorianWoelki** [comment]
There was a small bug. Hopefully, I've fixed it now.

**Comment by Mara-Li** [comment]
I checked the new version and yup everything is fine!

**Comment by FlorianWoelki** [comment]
Awesome nice to hear!

**Comment by Mara-Li** [comment]
Okay, for strange reason, after pull / yarn / node / yarn dev, and moved, the icon continue to disappear.

Here is my console : 
![image](https://user-images.githubusercontent.com/30244939/140903386-57ed8f46-0589-4b21-be1a-e1b356c255f7.png)

**Comment by FlorianWoelki** [comment]
Try to check it out now. Should be fixed now.

**Comment by Mara-Li** [comment]
fetch and rebuild from scratch, same error :<
I don't know if it's an error from my side when I build and move file or if it's the code :<

**Comment by FlorianWoelki** [comment]
Hmm... I don't have this error anymore. Can you look into your `data.json` file in /.obsidian/plugins/obsidian-icon-folder` and check if there is any value that has two prefixes in it? For example: `RiRiTrash`. You can remove this key-value pair and test it again if it exists. Because for me, everything works fine.

**Comment by Mara-Li** [comment]
Yes, all good with that !

**Comment by FlorianWoelki** [comment]
Hmm that's strange. I think that comes from the testing, it shouldn't be an issue in production.
