### ISSUE TITLE
The same icon is displayed.

### ISSUE THREAD

**Issue by minhuits** [FlorianWoelki/obsidian-icon-folder#141]
**Describe the bug**
The same icon is displayed.

**To Reproduce**
1. Add Spring related icons
<img width="770" alt="캡쳐 5" src="https://user-images.githubusercontent.com/58944350/209548057-27531284-4175-4506-998d-b8b13ccf5e1b.png">

2. See error
<img width="257" alt="캡쳐 6" src="https://user-images.githubusercontent.com/58944350/209548006-19d215a3-00bf-43e9-8eab-b27d9670a711.png">

**Expected behavior**
Show set icons

**Comment by FlorianWoelki** [comment]
This should be fixed in [2.0.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.0.0).
