### ISSUE TITLE
Thinking about a universal icon plugin...

### ISSUE THREAD

**Issue by FlorianWoelki** [FlorianWoelki/obsidian-icon-folder#144]
This plugin (`obsidian-icon-folder`) gained much traction in the last months and years.

I've been thinking about a universal icon plugin that allows you to integrate the loaded icons everywhere you want. Insert icons into your content, folders, files, and more. Obviously, much work must be done to achieve this goal. However, I would like to ask the community what they are currently using for enabling icons in their obsidian vault and what potential use cases are.

In addition, to a universal icon plugin, I'd like to create a library that can be easily used to create your own plugin based on this plugin so that you can easily extend your plugin with icons.

I am open to discussions and would like to hear your thoughts!

Cheers
Florian

**Comment by robertandrews** [comment]
Please approximate what Notion does.
Icon set at the page level is visible:
- Left-hand nav
- Adjacent to page title
- In any links to the page (eg wiki link titles, if it were Obsidian)

Nothing I have found for Obsidian does this, but it would make it so pleasing, friendly and familiar.

![IMG_1112](https://user-images.githubusercontent.com/3158787/211420961-738f4969-650e-4b9c-939a-d739a54db308.jpeg)
![IMG_1109](https://user-images.githubusercontent.com/3158787/211420761-f89b6c5f-0de9-4bda-a36d-ea15d94f105f.jpeg)
![IMG_1110](https://user-images.githubusercontent.com/3158787/211420775-db18f96c-a751-454b-9af6-8646226f8f69.jpeg)
![IMG_1111](https://user-images.githubusercontent.com/3158787/211420780-c2c25228-3cc9-427d-a62b-e8cc4e833a0d.jpeg)

**Comment by FlorianWoelki** [comment]
> Please approximate what Notion does. Icon set at the page level is visible:
> 
> * Left-hand nav
> * Adjacent to page title
> * In any links to the page - ie in-text links (eg wiki link titles, if it were Obsidian), databases... anywhere
> 
> Nothing I have found for Obsidian does this, but it would make it so pleasing, friendly and familiar.
> 
> Allow icon setting for both pages and folders.
> 
> ![IMG_1113](https://user-images.githubusercontent.com/3158787/211421881-643d57d3-b351-4742-8edd-1dfebae568a1.jpeg) ![IMG_1109](https://user-images.githubusercontent.com/3158787/211420761-f89b6c5f-0de9-4bda-a36d-ea15d94f105f.jpeg) ![IMG_1110](https://user-images.githubusercontent.com/3158787/211420775-db18f96c-a751-454b-9af6-8646226f8f69.jpeg) ![IMG_1111](https://user-images.githubusercontent.com/3158787/211420780-c2c25228-3cc9-427d-a62b-e8cc4e833a0d.jpeg)
> 
> See what the [Link Favicons](https://github.com/joethei/obsidian-link-favicon) plugin does for _external_ links...
> 
> ![IMG_1114](https://user-images.githubusercontent.com/3158787/211472776-7b7b1b31-e1d7-4b7b-a88f-d2a6b0940ab9.jpeg)

I like the suggestion, thanks! What do you think about the general idea of a universal icon plugin?

**Comment by robertandrews** [comment]
> I like the suggestion, thanks! What do you think about the general idea of a universal icon plugin?

To be honest, I don't understand the idea yet, maybe you can add some detail?

> I've been thinking about a universal icon plugin that allows you to integrate the loaded icons everywhere you want. Insert icons into your content, folders, files, and more.

I don't think I have a need to just arbitrarily insert icons into notes, but I would like pages and folders to have icons that _appear_ "universally".

**Comment by FlorianWoelki** [comment]
> > I like the suggestion, thanks! What do you think about the general idea of a universal icon plugin?
> 
> 
> 
> To be honest, I don't understand the idea yet, maybe you can add some detail?
> 
> 
> 
> > I've been thinking about a universal icon plugin that allows you to integrate the loaded icons everywhere you want. Insert icons into your content, folders, files, and more.
> 
> 
> 
> I don't think I have a need to just arbitrarily insert icons into notes, but I would like pages and folders to have icons that _appear_ "universally".
> 
> 
> 
> 

Yeah sure.
What I basically mean is that you can use your icons everywhere you want. So for instance, in the content of your files. In addition, other developers can easily integrate this plugin to add icons to their plugin etc. Maybe that makes more sense?

**Comment by robertandrews** [comment]
> Yeah sure.
> What I basically mean is that you can use your icons everywhere you want. So for instance, in the content of your files. In addition, other developers can easily integrate this plugin to add icons to their plugin etc. Maybe that makes more sense?

Personally, I'm not sure it's something I would benefit from, if it means just arbitrarily adding icons in content.

**Comment by xanahopper** [comment]
Yes, but using the SVG icon as the only choice is a catastrophe when synchronizing the vault with iCloud. One icon pack contains thousands of icon files; meanwhile, using icon font only require one (maybe two—font file and one extra map info file).
I know that the icon font is not recommended in web development, but I think the icon font is a better choice.
