### ISSUE TITLE
Show icons in tabs

### ISSUE THREAD

**Issue by catinwarmhands** [FlorianWoelki/obsidian-icon-folder#149]
Hi!

I think it would be nice to show file icons in tabs, here:
![image](https://user-images.githubusercontent.com/10079355/215270246-7cc1c9e2-a7a3-4ce6-b0d4-dcb1c78a1112.png)

Is it possible to add such feature?

**Comment by replete** [comment]
Nice to see this request already exists and there's a commit as this would be an excellent enhancement that would improve tab navigation.

Great plugin, really improves the experience of Obsidian. Thanks for your efforts.

**Comment by FlorianWoelki** [comment]
This is now officially released in [2.0.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.0.0). You can enable icons in tabs by going to the settings and toggling the button. Have fun with it! :)

**Comment by replete** [comment]
Superb work, @FlorianWoelki. This really helps with navigation when using multiple files with the same filename (e.g. YYYY-MM-DD). Thanks
