### ISSUE TITLE
Plugin cannot be updated

### ISSUE THREAD

**Issue by jsmm** [FlorianWoelki/obsidian-icon-folder#15]
This plugin cannot be updated from version 1.0.22 to next.

**Comment by FlorianWoelki** [comment]
What do you mean by `next` version? Version `1.0.22` is the newest one.

**Comment by jsmm** [comment]
The plugin notifies of a version 1.2.0 that fails to update.
![icon-folder_version](https://user-images.githubusercontent.com/2811090/140883036-78a4f11d-65fb-4009-890c-dd766444b0e5.png)

**Comment by FlorianWoelki** [comment]
I've messed around with `standard-version` a bit. It is not on `1.2.0`. Sorry, I've reverted the changes.

**Comment by jsmm** [comment]
It is solved. Thank you.
