### ISSUE TITLE
Edit regex rules

### ISSUE THREAD

**Issue by vorpalvorpal** [FlorianWoelki/obsidian-icon-folder#150]
**Is your feature request related to a problem? Please describe.**
Regexs are difficult to get right. It often takes a couple of goes. Alternatively, even if regexs were correct, they may need to later change if folder naming conventions change.

**Describe the solution you'd like**
Add an "edit custom rule" button next to the "delete custom rule" button

**Comment by FlorianWoelki** [comment]
This feature is now implemented in [v1.7.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.7.0).
