### ISSUE TITLE
1.6 can't manually add/change icons via filemanager

### ISSUE THREAD

**Issue by AndrewSunshiny** [FlorianWoelki/obsidian-icon-folder#151]
**Describe the bug**
When manually adding icons to existing icon pack, on next obsidian launch all listed in settings icon packs are gone. It requires to manually delete and then reinstall icon pack to fix this. It seems, only adding icons through `Add an icon` button works fine.

**To Reproduce**
1. Manually add an icon(s) inside icon pack folder.
2. Close and relaunch Obsidian.

**Expected behavior**
All new icons are added and listed with others after relaunch

**Screenshots**
I'm not sure if this exact error makes any impact here, it occurs when there are some icons / icon packs were added manually inside icons folder.
![image](https://user-images.githubusercontent.com/50839774/216792111-663de7fd-0a67-4137-8892-3ba6c360602a.png)

**Additional context**
OS Linux, Obsidian v1.1.9

**Comment by FlorianWoelki** [comment]
Hi there,
thanks for reporting.

Unfortunately, I am not able to reproduce this issue. 
Could you please tell me the exact steps, you've taken? What does manually mean? Could you also attach the SVG you are trying to add?

**Comment by FlorianWoelki** [comment]
Closing for now, because of inactivity.
