### ISSUE TITLE
Issues with Obsidian sync

### ISSUE THREAD

**Issue by keathmilligan** [FlorianWoelki/obsidian-icon-folder#162]
**Describe the bug**
Icon selections disappear when synchronized across multiple devices using Obsidian Sync service.

**To Reproduce**
1. Select icons for various folders/files
2. Open Obsidian on another device and allow it to sync.
3. Some icons will not be found on device or another and be replaced with their names.
4. You can fix the icons on one device, but they get messed up on another device during the next sync.

**Expected behavior**
Icons should synchronize across devices consistently.

**Comment by FlorianWoelki** [comment]
It's a problem with obsidian sync and the amount of icons that are stored.
Will be tracked in #153 and #159
