### ISSUE TITLE
Tabler icons support

### ISSUE THREAD

**Issue by jimfilippou** [FlorianWoelki/obsidian-icon-folder#166]
I would like to request (and I'm willing to help on this) for the addition of tabler icon pack provided here https://tabler-icons.io/

The download link is this https://github.com/tabler/tabler-icons/releases/download/v2.17.0/tabler-icons-2.17.0.zip but the structure is the following

<img width="309" alt="image" src="https://user-images.githubusercontent.com/6877046/234303556-3f150dfc-9618-4172-8788-1c098bd4a504.png">

You see the icons are inside the "svg" folder. Is it possible to integrate this and tackle this "issue" easily?

**Comment by FlorianWoelki** [comment]
It will be available in the next release as a default icon pack.

**Comment by FlorianWoelki** [comment]
Released in [v2.0.1](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.0.1).
