### ISSUE TITLE
Plug-in enablement failure

### ISSUE THREAD

**Issue by CallMeLD** [FlorianWoelki/obsidian-icon-folder#168]
If you click Enable, a message is displayed indicating that the function fails
![image](https://user-images.githubusercontent.com/49227091/235558382-b102d7d6-d433-41c3-bd1a-995ab5503fb3.png)
Now I have installed the following plug-ins, is it plug-in conflict?
![image](https://user-images.githubusercontent.com/49227091/235558642-038fa75c-bd3a-4724-be43-0212851f628c.png)
![image](https://user-images.githubusercontent.com/49227091/235558665-351f5699-88e7-497b-9323-dd9999c4371c.png)
![image](https://user-images.githubusercontent.com/49227091/235558686-bbcad185-238d-4759-907d-8cfce1159c40.png)

**Comment by FlorianWoelki** [comment]
Thanks for reporting.

Could you give the following details: which obsidian version and what the exact error is (see developer console for more information)?

**Comment by FlorianWoelki** [comment]
I'll close this issue for now.

It might be an issue with the combination of other plugins.
