### ISSUE TITLE
Broken since upgrading to Obsidian 1.2.7

### ISSUE THREAD

**Issue by replete** [FlorianWoelki/obsidian-icon-folder#170]
**Describe the bug**
Icons do not show since updating to Obsidian 1.2.7 from 1.1.16, and a javascript error is now showing in the console:

MacOS 13.3.1, Obsidian 1.2.7

**To Reproduce**
Upgrade to Obsidian 1.2.7

**Expected behavior**
Icons show as previously configured.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/812139/235753523-c8d05974-a180-4801-bae7-4e4a6cdb5d82.png)

After updating to Obsidian 1.2.7:
![Screenshot 2023-05-02 at 19 25 11](https://user-images.githubusercontent.com/812139/235752977-f5e15968-8177-4124-bb6d-dce47056653d.png)

**Additional context**

**Comment by Klemet** [comment]
Exact same issue on my side. I really love this plugin, so I hope that a fix is possible !

**Comment by gabrielcarus** [comment]
Same error on my side too, is really weird to imagine Obsidian without this plugin imo, hope is fixed soon

**Comment by KillyMXI** [comment]
Disabling the bookmarks core plugin made no difference for me.

Reapplying icons makes them appear but only until Obsidian restart.

**Comment by InvaderJ** [comment]
oh geez oh man my life is _over_ without my icons T____T

**Comment by edfus** [comment]
Looks like the Obsidian team removed the core plugin "starred" (StarredInternalPlugin) without prior notice, would be an easy fix but I've decided to disable automatic updates forever 😇

**Comment by looneyapache** [comment]
Same issue, both file color and icons are gone :(

**Comment by FlorianWoelki** [comment]
Everything should be now ready to go including [v2.0.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.0.0).

**Comment by replete** [comment]
Update worked superbly, thanks so much!

**Comment by DawsSauce97** [comment]
does this update apply to file colour? I still cannot change my file colour through the community plugin

**Comment by looneyapache** [comment]
Thank you!!!
