### ISSUE TITLE
Icon name showing instead of actual icon

### ISSUE THREAD

**Issue by bololodev** [FlorianWoelki/obsidian-icon-folder#171]
I believe it's the same as this https://github.com/FlorianWoelki/obsidian-icon-folder/issues/138

> I cannot reproduce this issue. For me this specific icon works fine.

I had just installed the plugin and the icon packs, set a few icons and restarted Obsidian, the same thing happened to me.

![image](https://user-images.githubusercontent.com/80776140/235814463-67c669cf-7320-4949-9f9f-effda626ae51.png)

I tried changing the icon and selecting the same icon again, it worked. 

EDIT: Apparently whenever you add a new pack, the icons only get renamed to camelCase after you restart Obsidian, so if you install a pack and change the icon of a file before restarting Obsidian it may save the icon name with it's original name (including dashes). The icons only get renamed when you restart Obsidian, so if the user alters the icons before they get renamed, it results in this issue.

This is how it looks in the `data.json`, if I set the icon before restarting Obsidian vs. after.

```
"Domains": "LiMouse-pointer-click"
```
After I installed some other pack the icons names changed:

```
"Domains": "LiMousePointerClick"
```

**Comment by FlorianWoelki** [comment]
What iconpack do you use? It seems to work fine with all the preset ones.

**Comment by FlorianWoelki** [comment]
So I've tested this with LucideIcons and could not reproduce this.

I was doing the following:
1. Download LucideIcons by browsing the icon packs
2. Setting lucide icon to a file
3. Reloading obsidian

Even when I download the icon pack, all the files directly get renamed.
