### ISSUE TITLE
Custom Icon Rules - allow to edit icon, reset color of a rule

### ISSUE THREAD

**Issue by KillyMXI** [FlorianWoelki/obsidian-icon-folder#173]
> **Is your feature request related to a problem? Please describe.**

After a rule is added, if I decide to change icon used for a particular regex - I have to copy the regex from the rule, delete it and create a new one with the new icon.

If I chose a color for a rule, then change my mind and want to get back to default - same story.

> **Describe the solution you'd like**

Change UI of each rule to allow "change icon" and "default color" actions.

Icon should probably be shown rather than named, and the click on it will call the icon selection dialog.

Not sure what is the best UI for the "default color" that doesn't involve a button with text, in case color picker offers no such feature.

> **Describe alternatives you've considered**

Copy regex from old rule, delete it and create a new rule - inconvenient.

**Comment by FlorianWoelki** [comment]
This is now released in [v2.1.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.1.0).
