### ISSUE TITLE
Icons dissapear when editing notes or closing Obsidian

### ISSUE THREAD

**Issue by DRD161** [FlorianWoelki/obsidian-icon-folder#174]
**Describe the bug**
After adding an icon to a note the icon will randomly disappear. This happens when I make changes to the note or when I close Obsidian. My icons folder path is as follows: .obsidian/plugins/obsidian-icon-folder/icons.

**To Reproduce**
1. Ad an icon to a note or folder
2. Make edits or close Obsidian
3. Icons disappear

**Expected behavior**
Icons should persist when making edits and closing Obsidian

**Screenshots**

**Icon showing**
<img width="228" alt="Screenshot 2023-05-04 at 12 08 04 PM" src="https://user-images.githubusercontent.com/29187448/236264879-c57b1691-88e6-4cb9-857f-51e38c0e3630.png">

**Icon disappears after closing Obsidian**
<img width="228" alt="image" src="https://user-images.githubusercontent.com/29187448/236265399-cfccb659-a95c-4ed5-ad0d-2dd3fa2628d8.png">

**Additional context**
Obsidian Version 1.2.7
Folder Icons Version 2.0

**Comment by FlorianWoelki** [comment]
I cannot reproduce this issue. Could you please describe which icons you use and try to find an error in the developer console?

**Comment by chrisk-7777** [comment]
This happened to me immediately after the latest Obsidian update. 
However, I uninstalled Folder Icons and reinstalled, and it has stated working again.

You may need to back up `.obsidian/plugins/obsidian-icon-folder/data.json` prior to doing the above, just in case.

**Comment by FlorianWoelki** [comment]
Ok, interesting. So the issue does not belong to this plugin?

**Comment by DRD161** [comment]
@FlorianWoelki it looks like it. I'll file an issue with the Make.md plugin and link back to this one so we can hopefully get this fixed. Bot had great plugins and it'd be awesome if they could play nice together lol. Thanks for your help!

**Comment by jp-cen** [comment]
There's a setting in make.md that solves this issue called Spaces Compatibility mode
