### ISSUE TITLE
Icon should change when the folder of a note changes (Inherit icons)

### ISSUE THREAD

**Issue by AB-boi** [FlorianWoelki/obsidian-icon-folder#178]
(I use Obsidian on my iPad.)
_I'm grateful for the Icon Folder plugin._ 
## The Background
Each of my folders has a different icon with inherit icons enabled. This way I can also use an icon for identifying my note type as it shows up nicely in the edge of stacked tabs like this - 
![2A9B2ACB-812E-4579-BED0-5826A5A0EEF4](https://user-images.githubusercontent.com/108968093/236693045-548b629b-0f97-4524-bbfc-3c7f2038fdcb.png)

## The Problem -
1) I create a note within a folder (in this case, 'Literature') and it inherits its icon, like this -
![80A9B737-BDF5-4399-9800-49807B5E2697](https://user-images.githubusercontent.com/108968093/236693152-6d964ca8-a95d-4517-ad72-c53aad991d06.png)

  Which is good, but
2) If it gets moved to a new folder with a different inheritable icon (in this case, 'Concepts'), it now doesn't take up the new icon in the sidebar (but this new icon still shows up correctly in the edge of a stack tab), like this- (Ignore 'The Book Thief' tab)
![17A88B91-C65A-457B-A489-E118968CC58D](https://user-images.githubusercontent.com/108968093/236693074-5727ee2e-4c84-4a92-a652-55d3dd667ed4.png)

## My Request/Suggestion -
1) Please make it such that a note (without a manually assigned icon) takes up an icon according to the folder that contains it and _even updates it upon moving the note into different folders_.

2) Also some people might want a note to retain the icon assigned by them manually. In which case give precedence to a manually added icon over an inherited icon (_It already does this, so maybe keep it that way ?_)

Thank you for your time @FlorianWoelki .

**Comment by FlorianWoelki** [comment]
Thank you for your suggestion. This is actually a bug and I'll fix that soon.

Regarding the second point: the icon you manually set should be always prioritized over the inherited icons.

**Comment by AB-boi** [comment]
@FlorianWoelki 
Hi !
Sorry to ping you like this but I am new to Github and I closed the issue by mistake. I have reopened it but I don't know if it's on the upcoming roadmap for fixes.

**Comment by FlorianWoelki** [comment]
This is now fixed in [v2.1.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.1.0).
