### ISSUE TITLE
Icon don‘t display in bookmark group

### ISSUE THREAD

**Issue by ribber** [FlorianWoelki/obsidian-icon-folder#179]
**Describe the bug**

I'm using the bookmark group feature to categorize my bookmarks, but I've noticed that the icon is not showing up

**Screenshots**

![图片](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/5986011/e82f67f3-e7d9-4d2f-9f5b-63d5bc39809f)

**Additional context**
Win ObsidianV1.2.8

**Comment by FlorianWoelki** [comment]
Fixed in [v2.0.1](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.0.1)

**Comment by Kribensisis** [comment]
Hey @FlorianWoelki looks like this is an issue again? Glad to close mine if you end up reopening this.
https://github.com/FlorianWoelki/obsidian-iconize/issues/654
