### ISSUE TITLE
suggestion: rename plugin 'Folder Icon'

### ISSUE THREAD

**Issue by daggers-camille** [FlorianWoelki/obsidian-icon-folder#18]
it's up to you, but on the obsidian discord and in the forums everyone tends to say 'folder icon plugin' when they bring up your plugin... might help to reduce confusion / help people find the plugin more easily :)

**Comment by FlorianWoelki** [comment]
Thank you for the suggestion! I was thinking about renaming the plugin and haven't found a name yet. The reason being is that you can also apply icons to files.
If you have ideas or something, feel free to tell me :)

**Comment by ShahriarKh** [comment]
Also, it's not just for folders, but for files too.

**Comment by FlorianWoelki** [comment]
Yeah but the problem is that obsidian icons plugin already exists :D

**Comment by FlorianWoelki** [comment]
Will be solved in #159
