### ISSUE TITLE
can't remove inhert icon in sub folder

### ISSUE THREAD

**Issue by liuxing7954** [FlorianWoelki/obsidian-icon-folder#180]
Sorry, I don't know why I can't upload the screenshot, but the procedure for reproducing the problem is very simple.

- level1 folder
  - level2 folder
  - level2 file

Set inhert icon on the folder level1
Delete inhert icon on folder level1
Set inhert icon on the folder level1
Delete inhert icon on folder level1

Multiple duplicate ICONS appear in level2

**Comment by liuxing7954** [comment]
![image.png](http://pic.wobuqu.icu/picgo/20230522104624.png) 
like this

**Comment by liuxing7954** [comment]
reopen client will resolve it

**Comment by FlorianWoelki** [comment]
This should be fixed in [2.0.2](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.0.2).
