### ISSUE TITLE
Icon color inconsistency

### ISSUE THREAD

**Issue by Valombreuse** [FlorianWoelki/obsidian-icon-folder#182]
**Describe the bug**
If you change the color of icons, only a few random icons actually change their color. Most keep their former color.
Note that I mainly use custom icons.
Note also that custom icons tend to keep their black (natural) color and do not seem to be impacted by color picker and themes. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by FlorianWoelki** [comment]
It's most likely related to your icons. Could you please give me some samples of your icons?

**Comment by FlorianWoelki** [comment]
Moving discussion to #181
