### ISSUE TITLE
the folder icons in "Bookmarks" overlap with the file names

### ISSUE THREAD

**Issue by CynthiaCAO777** [FlorianWoelki/obsidian-icon-folder#183]
After Obsidian v1.3.3 update, the file tree is indented and the folder icons in "Bookmarks" overlap with the file names...

**Comment by ribber** [comment]
I had the same problem

**Comment by FlorianWoelki** [comment]
This should be fixed in [2.0.2](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.0.2).
