### ISSUE TITLE
Obsidian v1.3.4 does not show Emoji icons

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [FlorianWoelki/obsidian-icon-folder#184]
**Describe the bug**
Obsidian updated to v1.3.4, when Emoji Style select None, the icon will disappear into a space placeholder.

<img width="552" alt="image" src="https://github.com/FlorianWoelki/obsidian-icon-folder/assets/62452364/a7cd9a7c-7a3d-4157-b241-1c1bc18de7bc">

**Comment by FlorianWoelki** [comment]
This is actually not a bug, it is intended because no Emojis means that no Emojis will exist in your vault.
