### ISSUE TITLE
Having folder icon enabled causes bookmarks to not work properly

### ISSUE THREAD

**Issue by Psypher1** [FlorianWoelki/obsidian-icon-folder#185]
When you add a bookmark and choose a group, it is supposed to go into the group. When icon folder is active, it just gets added to the top level. If I turn off icon folder, it works fine.

Also there is a weird thing happening with icon folder in the bookmark section of bookmarked files - they don't show the default icon when icon folder is on

**Comment by FlorianWoelki** [comment]
This should be fixed in [2.0.2](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.0.2).
