### ISSUE TITLE
[Feature] Group custom icon rules

### ISSUE THREAD

**Issue by minhuits** [FlorianWoelki/obsidian-icon-folder#187]
**Is your feature request related to a problem? Please describe.**
=> I want the ability to group custom icon rules.

**Describe the solution you'd like**
=> I want a grouping function like QuickAdd.
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/58944350/15221b2e-4aac-45b5-b904-c310928ec60a)

We recommend grouping by 'Folders', 'Files', 'All', 'Custom'.
If you set it as a folder with the change icon, it will move to folder grouping,
If set to a file, it will be moved to a group of files.
Customizations must be recognizable by their custom name.
Default is 'all'.

For example in my case I set attachments, canvas, templates, PDF etc in lib folder. And I want to set the icon group name to 'lib' and group the icon rules for Attachments, Canvas, Templates and PDFs in the same way.

**Describe alternatives you've considered**

**Additional context**

**Comment by FlorianWoelki** [comment]
I don't think that this will be part of this plugin because it has nothing to do with icons as far as I can tell.
