### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by vapensmianm149s** [FlorianWoelki/obsidian-icon-folder#188]
Not available after adjusting setting offset pixels
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/7703758/027b7edb-4835-453c-ad64-1574db05e530)
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/7703758/a8f97fb9-ee4f-4df5-aa46-76d7eeddf9db)

**Comment by FlorianWoelki** [comment]
Could you please be a little bit more descriptive? What did you do? What steps I can follow to reproduce etc.?

**Comment by vapensmianm149s** [comment]
I Adjusted icon left pixel -6or-11，Software cannot render，cannot be set.

**Comment by vapensmianm149s** [comment]
I Adjusted icon left pixel -6or-11，Software cannot render，cannot be set.
I used version 1.5 backups to overwrite and cannot restore.Updating later did not restore

**Comment by vapensmianm149s** [comment]
> Could you please be a little bit more descriptive? What did you do? What steps I can follow to reproduce etc.? 

I Adjusted icon left pixel -6or-11，Software cannot render，cannot be set.
I used version 1.5 backups to overwrite and cannot restore.Updating later did not restore

**Comment by FlorianWoelki** [comment]
I still don't really understand. Do you have a log of the developer console of obsidian?

**Comment by vapensmianm149s** [comment]
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/7703758/11f8e816-c3b6-447b-b8a3-4a1acd31bdfe)
[obsidian.md-1685801292046.log](https://github.com/FlorianWoelki/obsidian-icon-folder/files/11642942/obsidian.md-1685801292046.log)

I Adjusted icon left pixel -20

**Comment by FlorianWoelki** [comment]
Okay, I see the error now in the logs, thank you. This issue should be resolved in `v2.1.1` and is related to #189.
