### ISSUE TITLE
When a file / folder is moved, icon of parents disappear

### ISSUE THREAD

**Issue by Lisandra-dev** [FlorianWoelki/obsidian-icon-folder#192]
**Describe the bug**
When I move a file, for example move the folder in another parent, the icons disappear and I need to reload Obsidian.

**To Reproduce**
1. Set a icon for a folder
2. Create a file or a folder with an icon
3. Move in another folder the file.

**Expected behavior**
Icon must be kept when moving, a last for file that are untouched.

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/30244939/f74e03c6-b599-48bc-b377-d34862ba27a8)
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/30244939/a33cb020-efb9-4364-9311-1ffde76f4760)

**Additional context**
- Issue appear on Windows 11 Obsidian 1.2.7.
- Appear on drag and drop or using the obsidian moving command.
- Issue appear also on mobile

**Comment by FlorianWoelki** [comment]
Thanks for the report.

I cannot reproduce this issue with files. So moving files that have an icon from one folder to another should not break the file icon. However, I can reproduce an issue when moving a folder that has an icon into another folder. Is that what you meant?

**Comment by Lisandra-dev** [comment]
With file, did you try with renaming?

**Comment by FlorianWoelki** [comment]
> With file, did you try with renaming?

Renaming works fine for me. Maybe it was because of the change I did. Could you have a look at the recent change?

**Comment by Lisandra-dev** [comment]
Take a while to build the things on windows (maybe you could use cross-env to update the release cmd ? `mv` is not recognized. My tips is to create a js script to move the file)
But seems to works like a charm!

**Comment by FlorianWoelki** [comment]
> Take a while to build the things on windows (maybe you could use cross-env to update the release cmd ? `mv` is not recognized. My tips is to create a js script to move the file) But seems to works like a charm!
> 
> btw:
> 
> ```
> pnpm add -D copyfiles
> ```
> 
> Upgrade `release` to : ` "release": "npm run build && copyfiles -f src/styles.css manifest.json dist && move main.js dist\\",` can add support for multiple platform

You just had to use `pnpm dev` without `build` or `release`. So, I am not convinced that currently, I'll spend time on multi-platform compatibility for releasing. Thanks for the suggestion, though.

**Comment by FlorianWoelki** [comment]
I've released the fix in [v2.1.2](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/2.1.2). Thanks for reporting! :)
