### ISSUE TITLE
Default folder icon still exist

### ISSUE THREAD

**Issue by zjuyk** [FlorianWoelki/obsidian-icon-folder#194]
**Describe the bug**
After adding an icon for a folder, there is still a default folder icon. It seems that there is not just a replacement. 

**To Reproduce**
1. Install obsidian-icon-folder 2.1.2 form obsidian plugin management
2. Download remix-icons in plugin configuration
3. Right click on a folder and change icon

**Expected behavior**
I hope added icon can replace the default folder icon.

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/76436317/17eb87c4-b1c1-4a09-baeb-fa4fd4d7d5c2)

**Additional context**
OS: Arch Linux
DE: Plasma 5.27
Obsidian version: 1.3.5
Icon Folder version: 2.1.2

**Comment by FlorianWoelki** [comment]
I cannot reproduce that locally for my vault.
How did you exactly get these default folder icons?

**Comment by zjuyk** [comment]
This is my fresh vault, so no any custom css or other configuration. Here is my plugin list.

- Advanced Tables 
- Dataview
- Obsidian Git
- Style Settings
- Icon Folder
- Book Search
- Code Emitter

All of them are the latest version. The most possible confict item could be the theme setting. I am using Catppuccin them. Could you please try to reproduce again using a fresh valut? Thanks in advance!

**Comment by zjuyk** [comment]
It's Catppuccin theme which leads to this conflict. I should make a try to merge the conflict part. Anyway, thank you for your attention on my stupid issue.
