### ISSUE TITLE
Support icons for tags?

### ISSUE THREAD

**Issue by macintacos** [FlorianWoelki/obsidian-icon-folder#200]
**Is your feature request related to a problem? Please describe.**

I'd love to have icons for tags. I know that kinda goes against the point of this plugin, it feels like it's tangentially related enough to request it :)

**Describe the solution you'd like**

The same ability to select icons for folders, to be allowed for selecting icons for tags.

**Describe alternatives you've considered**

I've tried hacking CSS, but honestly it's just far too tedious.

**Comment by FlorianWoelki** [comment]
Sure, thanks for the request. Could you please describe a little bit more on what you would like to have? Specifically, where the icons are placed and what tags are.
