### ISSUE TITLE
Problem when using this with Obsidian Git

### ISSUE THREAD

**Issue by Xtron135** [FlorianWoelki/obsidian-icon-folder#201]
**Describe the bug**
So Obsidian Git is a plugin to automate push and pull the vault to github repo. Idk what is the max number but based on your plugin, I found out that the git push command can only push up to 300 commits. If we git push more than 300 commit, we will get "error: spawn enametoolong" and will not be able to commit and push the new change. So this is about the icon packs in your plugin. When we add icon pack from the 'Browse Icon Packs' button, every single icon is counted as 1 file, thus 1 commit. The only packs that have less than 300 icons are FAR and IB. So if I install other packs, I will get the error when using the Obsidian Git automation, as all of them have 1000+ icons. I still need to install FAR and IB separately, then git commit each time. If I install both of them in one go, then git commit, that would be around 400 icons = commits, thus will trigger the error.

I know that with FAR and IB together already have a lot of icons, but if you would like to improve this to make this plugin works perfectly with Obsidian Git, my suggestion is, could you please split the 1000+ icon packs into part by part, with 300 icons each? For example, FAB Part 1, or FAB Pack 1, then FAB Part 2 or FAB Pack 2 something like that. This would ensure that every single icon packs can be used with Obsidian Git with no problem.

**To Reproduce**
1. Setup a vault, and a file.
2. Make sure to have Obsidian Git plugin  installed and set up properly (all the creds, token and stuffs).
3. Then configure the automatic push for the Obsidian Git plugin.
4. Install Icon Folder plugin.
5. Add the icons packs other than IB and FAR.
6. Edit something on your notes
7. Let the git push try to push your update.
8. The error will appear

**Comment by FlorianWoelki** [comment]
This might be fixed in the newest update.
