### ISSUE TITLE
Mobile not working properly.

### ISSUE THREAD

**Issue by kbhbhk** [FlorianWoelki/obsidian-icon-folder#202]
**Describe the bug**

Not showing icon in mobile environment.
Setting a file's icon as **emoji** is working, but **SVG icon** not working.

And I also set the icon file path to `.obsidian/icons` as you recommended.

DESC:

- If emoji setting is 'None': Not showing icon, just a bit of padding left.
- If emoji setting is 'Native' or 'Twemoji': Showing the icon's file name.
- Desktop: fine

**To Reproduce**

Set SVG icon (not emoji) and check it in mobile Obsidian.

**Expected behavior**

**Screenshots**

Desktop:

![000001](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/130442702/5294b143-03a8-4d78-a3d6-af91674971d9)

Mobile:

![000002](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/130442702/24ba16bd-c386-447e-9f92-482318e3272a)

![000003](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/130442702/c76626d3-350d-4272-89dc-854fa1ce9de4)

**Additional context**

**Comment by kbhbhk** [comment]
edit: sorry, it's working now somehow. I think it was occurred by delay of iCloud sync. Sorry for the misunderstanding and appreciate about this plugin! Now I'm closing this issue.

**Comment by kbhbhk** [comment]
hmm I think it's still happening... And I have no idea why it's not working.
Is this just for me? Does anyone have the same problem here?

**Comment by kbhbhk** [comment]
Right now in mobile, bookmarks tab showing the icons, but just not for the file navigation tab.

**Comment by bwya77** [comment]
following, I am also experiencing this

**Comment by kbhbhk** [comment]
Ok I see. Sorry for the duplicate issue, I didn't know. 😭
Thanks a lot!
