### ISSUE TITLE
icons keep disappearing after sync and restart

### ISSUE THREAD

**Issue by XVItokaz** [FlorianWoelki/obsidian-icon-folder#206]
I have sync and running between two computers I have obsidian installed. Macbook and PC windows 10.
My issue is that i don't get the icons to stay between devices after syncs, as soon as I add icon on one device, and after adding and check that obsidian sync, and i restarts (app) on both, it stays on the first i added the icons on, but not synced to the other device. Let say from PC to Macbook.

Tried starting from scratch on both devices, added icons on one device and then the sync worked.

But after a while when I "usually" add new icons to obsidian via my PC, and then sync on both devices, and for some reason need to add a new icon when i´m only on my Macbook, then that icon is there after sync, but the one i added on my PC is gone after i restart the app.

Also tried to reinstall icon pack on both, but that does not help.

Both icon Pack folder have the same path, meaning:
.obsidian/icons

As extra note, i have all syncs turned on for both selective sync and vault configuration sync

I also have exact same setting for Icon Folder settings on both devices

As example:

I have on both devices same setting, no icons at all on same category, as down below under Machine Learning

I add icons on 3 folders/text, marked as yellow in the picture, and then waiting for sync on both devices, close down obsidian app on my pc (i need to close the computer when i go to sleep :-) ) and when i restart is not synced to my app in my macbook and still there on my obsidian on my PC.

So, i add 3 icons before syncing, after syncing it left on my PC where i added them
![1](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/121265451/30028906-6601-4505-a940-7e58de595d8d)

But empty on my Macbook. both checked that sync is done

And after i have waited for sync and restarted the app, nothing in my Macbook (down below), still on my PC:
![Skärmavbild 2023-08-08 kl  21 20 28](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/121265451/0ef35a84-c568-4345-a28e-102aabcec90b)

That's the first problem, the second is that, if I now have to work on my macbook and then add an icon, as highlighted in turquoise, and sync (picture above), then that icon remains in my macbook obsidian app still, but in my PC and obsidian nothing, and that is not only that it is not synced, also the three i added icons (from the first picture) plus all the other icons under machine learning are gone?!?

![2](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/121265451/5f3e88ea-4d8b-4f4b-870a-6be566ff182c)

I need to understand one thing, maybe i have missed that completely, but can´t i add icons on one device, sync and even if the sync not working, add a new icon on the other device?

Now is a mess for me, but then again, maybe i´m doing something wrong?

**Comment by DesmondSylin** [comment]
I have same issue here. I dont know why Obsidian Sync tring to delete icon files on remote after sync once. It caused other devices lost icon files.

**Comment by FlorianWoelki** [comment]
Thanks for the detailed problem description!

It seems to be that it is a general problem in syncing and could be probably solved with #153.
I am actively working on the new syncing mechanism, so stay tuned for that.
