### ISSUE TITLE
Icon List Blank (Incompatibility with Front Matter Title plugin)

### ISSUE THREAD

**Issue by Aetherinox** [FlorianWoelki/obsidian-icon-folder#211]
**Describe the bug**
I've noticed over the last few weeks, occasionally the icons will not load at all when I attempt to change / add an icon to a folder. It's very random and doesn't happen all the time. I have Font Awesome icons installed (I own Pro) and I've confirmed that the icons are indeed in the folder. I even added one of the predefined icon packs to make sure it creates the folder and adds the icons; which it does, but it changes nothing.

Also re-loaded Obsidian, same result.

**To Reproduce**
Unknown, issue happens at random. Just attempting to add a new icon to a folder and/or file all has the same result.

**Expected behavior**
Icons show in the list for me to select from.

**Screenshots**
![1](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/118329232/4e1f07b8-1c32-421e-9cbc-bc8f31b41123)
![2](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/118329232/8562ac41-c5f8-4d5f-96b9-6f3a90858b55)

**Additional context**
Plugin Version: v2.1.2
Obsidian Version: v1.3.7
OS: Windows 11 Pro

**Comment by FlorianWoelki** [comment]
Will close this for now because no additional work is required on my end.
