### ISSUE TITLE
Icon Folder plugin is desinstalled after closeup on Mac OS

### ISSUE THREAD

**Issue by pwjohnson** [FlorianWoelki/obsidian-icon-folder#212]
**The Icon Folder plugin needs reinstalling each time I restart Obsidian**
This problem is self-understandable. Each time I close and reopen Obisidian on my MacBookPro, on Mac OS, the Icon Folder doesn't appear in the list of Community Modules. I have to reinstall it and activate it again. However, it finds my already installed folder icons once I re-activate it.

**To Reproduce**
1. Quit Obsidian on Mac OS, while Icon Folder plug in has been installed and activated
2. Open Obsidian on Mac OS.
3. The icons don't appear next to the folder. Checking in Community Plugins in my Prefefences shows that Icon Folder is not installed. All other of my community plugins (24) are there and activated for those I chose to activate.

**Expected behavior**
Icon Folder should reappear at each start of Obsidian on Mac OS.

**Screenshots**
Screenshots wont be helpful here.

**Additional context**
I have Sync activated and the plugin shows correctly on my (only) other device where Obsidian is synchronized through the programs Sync service. Even while it was deactivated on the latter (for 2 weeks), the plugin had the same behavior on the computer.

**Comment by FlorianWoelki** [comment]
Hey there,

I am not sure if this is an issue with the syncing mechanism or the plugin. For me, the plugin activates/deactivates as expected. However, it might be an issue with the syncing mechanism. I am currently working on a fix and this will be tracked in #153
