### ISSUE TITLE
Is it possible to set the rule for file type?

### ISSUE THREAD

**Issue by funamorisenji** [FlorianWoelki/obsidian-icon-folder#219]
My question is it possible to set a rule for a file type. For example If file is PDF, I want a specific Icon to be set for all the file that is `.pdf`. If it possible, please tell me how to do it.

**Comment by FlorianWoelki** [comment]
It should be possible. Please ask this in the [discussions](https://github.com/FlorianWoelki/obsidian-icon-folder/discussions) because it is not an issue and more like a question.
