### ISSUE TITLE
The latest update (v. 1.0.51) makes the command pallet in squares  

### ISSUE THREAD

**Issue by Liong1976** [FlorianWoelki/obsidian-icon-folder#22]
I am in Legacy Editor, on Windows. Obsidian v. 0.13.16. I have tried in the Obsidian original theme and the command pallet still shows in squares  (see screenshot).

![image](https://user-images.githubusercontent.com/88898230/147426163-e85eb46c-a51a-447b-a7a3-49d6033b4139.png)

When I disable the Icon Folder plugin, the command pallet is back to normal.

![image](https://user-images.githubusercontent.com/88898230/147426227-9af774c4-55d1-4787-beb2-8f51b50c3834.png)

I found out that all suggesters including `Recent Files` are also in squares.

**Comment by FlorianWoelki** [comment]
Thank you for reporting this bad issue. It should be fixed now with version [1.0.52](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.0.52)

**Comment by Liong1976** [comment]
Thanks, @FlorianWoelki!
