### ISSUE TITLE
[BUG]: Inheritance for folder doesn't work

### ISSUE THREAD

**Issue by Lisandra-dev** [FlorianWoelki/obsidian-icon-folder#220]
**Describe the bug**
My tree looks like that:
```
.
└── root/
    └── _REFERENCES/
        ├── Folder image 1/
        │   └── image.png
        ├── Folder Image 2/
        │   └── image.png
        └── simple image after REFERENCES.png
```

The icon doesn't apply on folder image, but work the file.

**To Reproduce**
Apply inherit icon on a folder

**Expected behavior**
The icon apply on the folder

**Screenshots**
OLD:
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/30244939/8b6b37c1-aa34-4a68-9b85-741424850833)

NEW:
![image](https://github.com/FlorianWoelki/obsidian-icon-folder/assets/30244939/c6b138ff-db15-460c-bb1c-959d08bce4ba)

**Additional context**
Tested on sandbox vault

Some investigation:
- Bug was introduced by commit d1cdc47
- Seems to be linked to line 77-87 : https://github.com/FlorianWoelki/obsidian-icon-folder/blob/d1cdc47e2e8635eb9e4b2f0d138f37a47b0b6623/src/lib/inheritance.ts#L76-L87
```diff
      for (const [path, fileItem] of Object.entries(fileExplorer.fileItems)) {
        // Checks if the file is in the folder and not a directory.
-       if (fileItem.file.parent?.path !== folderPath) {
-          continue;
-        }
        

-       const isFolder = (fileItem.file as TFolder).children !== undefined;
        const inFolder = path.includes(folderPath);
        const hasIcon = plugin.getData()[fileItem.file.path];
-       if (!inFolder || hasIcon || isFolder) { 
+      if (!inFolder || hasIcon ) {
          continue;
        }

        addIcon(fileItem);
      }
```

**Comment by FlorianWoelki** [comment]
Thanks for the report. This is in theory intentional and is not a bug because it should inherit only all the files in the directory.

**Comment by FlorianWoelki** [comment]
Yeah that makes definitely sense, but then you can also you custom rules right?

**Comment by FlorianWoelki** [comment]
A PR and reverse of the code doesn't make sense because this fixes a different issue. I'll see what I can do!

**Comment by Lisandra-dev** [comment]
No!
I mean, a PR for adding a new option in the custom rules, so the regex can be applied on the filepath instead of the filename only :>
