### ISSUE TITLE
[BUG] 2.2.0 Icon not found

### ISSUE THREAD

**Issue by Lisandra-dev** [FlorianWoelki/obsidian-icon-folder#221]
**Describe the bug**
I updated to the 2.2.0, with deleting and recreating all my icons for the new sync processing. After readding all my icons manually because of the name changing, no icons added by pack are found.

**To Reproduce**
1. Download icon pack
2. Add a icon to a folder
3. Reload obsidian

**Expected behavior**
The icon is keep.

**Screenshots**
https://github.com/FlorianWoelki/obsidian-icon-folder/assets/30244939/1f9611da-4130-49f4-9cd3-6a8b06543785

**Additional context**
Note: The bug is caused by the name generated and registered.

In the folder, the file is named with removing hyphen and uppercased, but it was registered WITHOUT the normalizedName.

**Comment by FlorianWoelki** [comment]
Thank you for the report. Could you please add a small reproduction directory with the files so that I can reproduce this locally?

**Comment by Lisandra-dev** [comment]
It's from the integrated icon packs "remix-icons", adding the icon "u-disk-line". I don't understand what do you mean by small reproduction.
Do you want a `data.json` or the folder generated by your plugin ?

**Comment by FlorianWoelki** [comment]
> It's from the integrated icon packs "remix-icons", adding the icon "u-disk-line". I don't understand what do you mean by small reproduction. Do you want a `data.json` or the folder generated by your plugin ?

No thank you the icon name was actually the key to reproduction :D I'll fix this asap.

**Comment by Lisandra-dev** [comment]
Works like a charm, ty!
