### ISSUE TITLE
[FR]: Add boxicons

### ISSUE THREAD

**Issue by Lisandra-dev** [FlorianWoelki/obsidian-icon-folder#223]
**Is your feature request related to a problem? Please describe.**
I, to be honest, appreciate the icon from [boxicons](https://boxicons.com/). Using the old behavior of the plugin, I downloaded all the icons from it, use a path excluded from Obsidian Sync, and just move the folder between my computer, iPad and Iphone (pain in ass). The new behavior of the plugin allow me to sync my folder icons… But, well. The boxicons is a folder with ~1000 files, so obviously, sync doesn't like that.

I would like to use the new sync methods on this folder, but it only work for iconPack added by the plugin (I think?). 

**Describe the solution you'd like**
A new custom icon pack for Boxicons.

**Describe alternatives you've considered**
Well, see description of the problem UwU !

Alternative: allow using the new syncing methods with custom folder.

**Additional context**
- [Boxicons Usage](https://boxicons.com/usage)
- Problem: as far I know, no zip download complete is offered/hosted by Boxicons, as you need to use gumroad to download all icon (so you need to first set an email). A solution can be a custom / fork of the github and create a release? I don't find any fork+ZIP. Maybe using `https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fatisawd%2Fboxicons%2Ftree%2Fmaster%2Fsvg` can work ?
- I made a fork with a release including zip file, and tested with adding this to `iconPack.ts`:
```ts
  boxicons: {
    name: 'boxicons',
    displayName: 'Boxicons',
    path: 'svg',
    downloadLink: 'https://github.com/Lisandra-dev/boxicons/releases/download/v2.1.4/svg.zip',
  },
```

**Comment by FlorianWoelki** [comment]
Well, you can always zip your icon pack so that it is available with the new syncing mechanism.

But I think this would be a good user experience addition to have the functionality that the custom icon packs can be created with a zip.

**Comment by Lisandra-dev** [comment]
Good to know! Ty!

**Comment by simonfossom** [comment]
FYI: if I zip my icons and don't add them in settings - I have no problem.
