### ISSUE TITLE
[Bug] Rules are classed in alphabetical order, making impossible to overwrite rules

### ISSUE THREAD

**Issue by Lisandra-dev** [FlorianWoelki/obsidian-icon-folder#226]
**Describe the bug**
All my rules that starts with `.` are on top. It's impossible to change their order by deleting, as it use path. So, for example, my rules `\.md$` will **always** before my rule `Pouvoirs`, as the plugin "take first" i can't reordering the things :<

**To Reproduce**
1. Set a custom rules starting by a point
2. Set another custom rules 
3. Try to delete the first to set it after the new, and see that it will always before the new. Also, the order is reset when changing the file type application

**Expected behavior**
The plugin should keep order of registering

**Screenshots**
/

**Additional context**
Linked to #71 

As they are just list, a button before/after with list reordering could work

**Comment by FlorianWoelki** [comment]
Isn't this a duplicate to #71?

**Comment by Lisandra-dev** [comment]
I don't think so. This behavior is new to me to be honest!

**Comment by FlorianWoelki** [comment]
Okay but the solution would be simply the ability to reorder custom rules right?

**Comment by Lisandra-dev** [comment]
I need to test in my own reordering before reply!

**Comment by Lisandra-dev** [comment]
Okay so, I implemented a ordering using the list, but I needed to remove the `getSortedRules` because it sorted by alphabetical. 
It's not probably the best because you know well better than me how you want to display this, but I make a PR with my own implementation!

**Comment by FlorianWoelki** [comment]
Closing because of #71
