### ISSUE TITLE
css breaks command palette

### ISSUE THREAD

**Issue by M3NIX** [FlorianWoelki/obsidian-icon-folder#23]
The introduction of the new css code from #20 breaks the appereance of all other prompts e.g. the command palette (`Ctrl+P`) from the core plugins.
![image](https://user-images.githubusercontent.com/24652680/147426218-38e5ce14-5aff-46bb-ba8e-a7325e5d01be.png)

**Comment by insecurejezza** [comment]
![Screen Shot 2021-12-27 at 4 32 12 pm](https://user-images.githubusercontent.com/70424851/147439028-13e0d025-eeb8-46e7-a9e2-0c07e8e108ae.png)

I have also encountered this issue.

**Comment by FlorianWoelki** [comment]
Thank you for reporting this bad issue. It should be fixed now with version [1.0.52](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.0.52). Please reopen this issue, if it still occurs.
