### ISSUE TITLE
Some Emojis aren't working correctly

### ISSUE THREAD

**Issue by ShahriarKh** [FlorianWoelki/obsidian-icon-folder#24]
For example, the Japan Flag 🇯🇵 

Showing correctly in Modal:
![image](https://user-images.githubusercontent.com/31452340/147504908-e750024a-f2ed-4435-b98f-4cd2dd07ee8d.png)
Not showing correctly in sidebar:
![image](https://user-images.githubusercontent.com/31452340/147504935-a0257a41-f9f4-44c7-a928-bd5014068b98.png)

I guess this is related to Windows, but it's showing correctly in Modal 🤔

**Comment by FlorianWoelki** [comment]
Thank you for reporting this issue! There was some wrong parsing. It should be fixed with the version [1.0.53](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.0.53)
