### ISSUE TITLE
Oversized folder icons in file explorer

### ISSUE THREAD

**Issue by jsmm** [FlorianWoelki/obsidian-icon-folder#26]
Hi.  Huge icons appear in Obsidian's file explorer, as in the image below.

![icon-folder](https://user-images.githubusercontent.com/2811090/147687761-387c98c4-f678-442d-989b-9bcd47c0acc7.png)

Icon Folder 1.0.54
Obsidian 0.13.16
macOS 12.1

**Comment by FlorianWoelki** [comment]
Thank you for reporting this issue! 

Is it possible to provide a reproduction way, so I can reproduce your issue?

**Comment by Rubecks** [comment]
I'm having the same problem. You just need to select a new icon for a folder using the most recent version. The issue is the lack of height and width tags on the svg element. Both are undefined on the new icons, but keeps the 16px on the old ones.

I fixed it with this css snippet:

```
.obsidian-icon-folder-icon > svg {
	height: 16px;
	width: 16px;
}
```

**Comment by FlorianWoelki** [comment]
So the problem is just a lack of backward compatibility. The reason being is that now the size and the style of the icons are customizable.

**Comment by jsmm** [comment]
It is solved, after choosing icons anew. 
Thank you, @Rubecks
