### ISSUE TITLE
Not able to use twemoji

### ISSUE THREAD

**Issue by technicalpickles** [FlorianWoelki/obsidian-icon-folder#28]
Hey there, twemoji was after I had initially found out about this plugin, so I was eager to try it. It's not quite working as expected for me though.

I read the notes in README.md:

> Right-click the folder
> Click Change icon
> Open your OS-specific emoji dialog
> Select the option Use twemoji emoji

Here's me trying to set 🚀 as a folder icon:

https://user-images.githubusercontent.com/159/147838349-92827bf8-c1ce-4cc0-a953-323ab01aa05c.mp4

Maybe I am misunderstanding the instructions?

**Comment by FlorianWoelki** [comment]
Hey thanks for the video.

What version of obsidian icon folder do you use? Maybe the issue is resolved when you update the plugin to the newest version?

**Comment by technicalpickles** [comment]
1.0.54 which is the latest as far as I can tell

![CleanShot 2022-01-01 at 17 39 21](https://user-images.githubusercontent.com/159/147861564-9259bdf8-da09-4c39-a8e2-929c9a8b898b.png)
l

**Comment by FlorianWoelki** [comment]
Pretty strange behavior. Could it be that some other plugin is interfering with the results?

**Comment by technicalpickles** [comment]
I hav a number of plugins, so definitely plausible.

What does it look like when it's working?

**Comment by FlorianWoelki** [comment]
It should look like this:

![image](https://user-images.githubusercontent.com/20746070/148027666-43dc6db9-d53a-4273-899d-1ad9af42dc99.png)

**Comment by technicalpickles** [comment]
I tried turning off all my other plugins, and got the same behavior. I also tried changing to the default theme in case it was a styling thing, but that didn't help either.

**Comment by FlorianWoelki** [comment]
Hmm. Did you use the latest version in the video? Because the modal does not look right. It should look like this:
![image](https://user-images.githubusercontent.com/20746070/148100311-b8588fbc-25e7-4745-a137-f15341f9b8fb.png)

**Comment by technicalpickles** [comment]
I swear I had upgraded Obsidian, but it seems like it did not take effect. After doing so, I get the view you shared, and icons work ❤️
