### ISSUE TITLE
Giant icons

### ISSUE THREAD

**Issue by yangauthier** [FlorianWoelki/obsidian-icon-folder#29]
Hey @FlorianWoelki and thank you for your Obsidian plugin. For the last couple of days, it has had a strange behavior though, resulting in the issue captured below.
![Obsidian_yK4oVhMhem](https://user-images.githubusercontent.com/44909764/147913323-73b5a3f6-3cef-4e37-91b4-cd8ac05fb59f.png).

I tried updating (v 1.0.54), disabling / reanabling but it didn't work out. Any clue why the plugin stopped working ? Cheers.

**Comment by FlorianWoelki** [comment]
Hey thanks for reporting this issue.

Can you please check, if it is related to #26 ?

**Comment by yangauthier** [comment]
Yes, it looks like #26 but removing / choosing new icons doesn't solve the problem. Plus each icon I had chosen now shows in the form of plain text (RiRiBriefcaseLine for instance). I saw the CSS trick to solve the issue but I don't know how/where to insert the CSS code.

**Comment by FlorianWoelki** [comment]
Right now, I am not able to reproduce this issue in any way which is kind of a weird thing. From which version did you update? Because in the newest version, you can now customize the size of the icons. Maybe try changing that to fix the issue?

**Comment by yangauthier** [comment]
I hadn't seen in the plugin settings that you could change the size of the icons. I just changed the size of the icons to 10px, then back to 16 and assigned icons to my folders all over again and everything seems to be working now. Thanks !
