### ISSUE TITLE
[Suggestion] Quicker access to frequently used or recently used icons

### ISSUE THREAD

**Issue by emilyeserven** [FlorianWoelki/obsidian-icon-folder#32]
It would be nice to have faster access to frequently used icons. Could potentially be in the form of a row or two of icons in the dialog that pops up when users want to add an icon.

**Comment by FlorianWoelki** [comment]
Lovely idea! The question is how many recent icons would be saved? What makes sense? 5 or 10?

**Comment by emilyeserven** [comment]
Almost a cop-out answer, is it possible to add it as a plugin setting?

Otherwise, maybe 10, because I'm not sure how many people actually scroll that much to find icons as opposed to just looking them up via text.

**Comment by FlorianWoelki** [comment]
Makes sense yeah :D it is possible!
I think I will just use 5 as a default value. I will try to add this feature asap :) thanks for the suggestion!

**Comment by FlorianWoelki** [comment]
So the feature should be implemented. If you want, you can test it. I will try my best to release it soon!

**Comment by FlorianWoelki** [comment]
This feature was released in version [1.0.6](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.0.6)
