### ISSUE TITLE
[BUG] New update broke icon sizes

### ISSUE THREAD

**Issue by veradrawer** [FlorianWoelki/obsidian-icon-folder#33]
Currently using 1.0.6 on Obsidian 0.13.14.
Some icons won't load (see image below) while the rest are at their native size.

Bug persists with all themes. 

![imagen](https://user-images.githubusercontent.com/75331117/149999115-9dd4cb7b-89aa-4dd1-be15-cb917f2afb58.png)

**Comment by FlorianWoelki** [comment]
Is it related to issue #30 ?

In addition, is there any error in the console?

**Comment by veradrawer** [comment]
I confirm it's the same issue.
I solved it by uninstalling the pluging and reinslling again, yet I lost all icon settings as expected.

**Comment by FlorianWoelki** [comment]
I will close it for now.
