### ISSUE TITLE
Add possible emoji picker or native emojis

### ISSUE THREAD

**Issue by FlorianWoelki** [FlorianWoelki/obsidian-icon-folder#34]
Should be possible to use native emojis or select others from other systems using an emoji picker like: [Emoji Mart](https://missive.github.io/emoji-mart/).

**Comment by huyz** [comment]
At the very least, it could be possible to type any arbitrary unicode character. If we had this capability, users could use the built-in system way to type in unicode emojis, e.g.: https://www.makeuseof.com/tag/type-emoji-mac/
Maybe this would require little dev effort.

**Comment by SamAriafar** [comment]
I agree! I used to add emojis in the name of my files/folders, but as you know they end up in the filesystem which brings issues to remote file syncing. I prefer using this plugin instead, but I rather see native emojis than Twitter-styled ones as the native version looks better.

**Comment by FlorianWoelki** [comment]
Closing because native emoji selection is currently possible and supported.
