### ISSUE TITLE
[Mobile] Once the selected icon is in the "Recently used Icons" item the whole display template will drop

### ISSUE THREAD

**Issue by ivanmood0** [FlorianWoelki/obsidian-icon-folder#35]
Once you select any icon and it will be in the "Recently used Icons" item - the whole display template will drop.

![Screenshot_20220127-114758__01](https://user-images.githubusercontent.com/79835684/151337249-f74e64e2-ce60-465c-9929-aa483a2e03f8.jpg)

**Comment by FlorianWoelki** [comment]
Thanks for reporting this issue! It should be fixed now, with [1.0.61](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.0.61).
