### ISSUE TITLE
Renabling plugin causes double icons

### ISSUE THREAD

**Issue by ScottKillen** [FlorianWoelki/obsidian-icon-folder#36]
If you disable the plugin, the folder icons remain.

If you reenable the plugin, the folder shows a double icon on files that have an icon on them.

![double icon](https://user-images.githubusercontent.com/1509989/151714398-88405bcc-df89-4d0f-90de-fa6cac6a16d0.png)

**Comment by FlorianWoelki** [comment]
Thanks for reporting this issue! It should be fixed now, with [1.0.61](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.0.61).
