### ISSUE TITLE
Lost folder icons after last upgrade to icon shortcodes

### ISSUE THREAD

**Issue by namtrah** [FlorianWoelki/obsidian-icon-folder#45]
Not sure which version I was on, but after upgrading to latest obsidian-icon-shortcodes (0.8.4) I received the following error and lost all my folder icons saved to my folders
```
loading Icon Shortcodes
VM221:42252 Uncaught (in promise) TypeError: Cannot destructure property 'basename' of 'app.workspace.getActiveFile(...)' as it is null.
    at instance$1 (eval at <anonymous> (app.js:1), <anonymous>:42252:8)
    at init (eval at <anonymous> (app.js:1), <anonymous>:3887:11)
    at new SideTree (eval at <anonymous> (app.js:1), <anonymous>:42317:3)
    at TreeView.draw (eval at <anonymous> (app.js:1), <anonymous>:42347:21)
    at refreshIndex (eval at <anonymous> (app.js:1), <anonymous>:35414:94)
    at async eval (eval at <anonymous> (app.js:1), <anonymous>:64349:17)
126app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'basename')
    at eval (eval at <anonymous> (app.js:1), <anonymous>:42256:59)
    at t.e.tryTrigger (app.js:1)
    at t.e.trigger (app.js:1)
    at t.trigger (app.js:1)
    at t.activeLeafEvents (app.js:1)
    at a (app.js:1)
```

Opening in his github as well. https://github.com/aidenlx/obsidian-icon-shortcodes/issues/33

**Comment by Mara-Li** [comment]
Try using this [main.js](https://gist.github.com/Mara-Li/e8f8181055658c33c5979304b07abe19) file for icon folder. I build it based on the fork of Alx.

**Comment by FlorianWoelki** [comment]
Should be closed now with the newest release.

**Comment by namtrah** [comment]
Hi Florian, maybe I am doing something wrong, but I updated to the latest release and now only half of the icons I am using are still there. Since you exported your icons into packs, did you leave out some basic icons. I don't want to publicly send a picture here, but I am missing the following (their names as shown in the folders when missing): 
FasCog
FasProjectDiagram
RiRiGroupLine
RiRiCustomerServiceFill
RiRiStickyNoteLine
RiRiToolsLine
RiRiMedia2Fill

I am certain there are more, but these are the ones I use in my Folder Icons. I can DM you a picture on Discord, if you are there. Maybe there are now fewer icons in the free set? I am not sure if this is a bug or WAD with the new icons packs having fewer icon choices than before.

**Comment by FlorianWoelki** [comment]
> Hi Florian, maybe I am doing something wrong, but I updated to the latest release and now only half of the icons I am using are still there. Since you exported your icons into packs, did you leave out some basic icons. I don't want to publicly send a picture here, but I am missing the following (their names as shown in the folders when missing): FasCog FasProjectDiagram RiRiGroupLine RiRiCustomerServiceFill RiRiStickyNoteLine RiRiToolsLine RiRiMedia2Fill
> 
> I am certain there are more, but these are the ones I use in my Folder Icons. I can DM you a picture on Discord, if you are there. Maybe there are now fewer icons in the free set? I am not sure if this is a bug or WAD with the new icons packs having fewer icon choices than before.

I think I did not leave anything out. It could be that the version I was using was older than the current versions. I've noted that on the fontawesome circle as well.

**Comment by namtrah** [comment]
Strangely, it was working previously (I had found the icon and used it) when there were no icon packs. Now using Icon Packs, these icons are longer to be found. And not only the FA pack, but also the Remix Icons where I saw many lost after the update using icon-packs.

**Comment by namtrah** [comment]
Maybe they were renamed from what you were using. I just double checked. In FA, there is a solid icon called "Gears" instead of Cog. and the "ProjectDiagram" is called diagram-project...So maybe you named them privately something differently and they are still there just that I cannot find them because of a diversion in naming?

**Comment by namtrah** [comment]
In fact, I did find all the Remix icons. after looking. their names were fine. And at least those two Font Awesome icons just had their names changed from previous. (in Obsidian at least).

I see no issue, but you may want to tell people that they should check with the font provider to ensure that they have the right name if using the new icon packs.
