### ISSUE TITLE
Custom icons not displayed correctly

### ISSUE THREAD

**Issue by icebruce** [FlorianWoelki/obsidian-icon-folder#48]
**After loading a custom icon set, a lot of the icons are displayed incorrectly**

**Steps to reproduce**
1. Download custom icon set -> https://github.com/icons8/flat-color-icons
2. Navigate to Icon Folder settings
3. Created new Icon pack (e.g. name it Icons8)
4. Click edit
5. Navigate to folder with the list of unzipped .zvgs, select all and apply
6. Wait for icons to be loaded
7. Edit a file to change the icon

**Expected behavior**
The icons should be displayed and displayed as per original design.

**Actual results**
-Some icons are grey in color, and not per original design (i.e. colored). Perhaps it is because it is inheriting the icon design from a different source, other than the actual loaded icon?
-Some icons show as empty

**Screenshots**
![image](https://user-images.githubusercontent.com/66655064/160021349-b1e43bd8-f552-41eb-a1ea-9d002789967b.png)

**Comment by FlorianWoelki** [comment]
Fixed within the new release.
