### ISSUE TITLE
Icon not display in new version 1.1.0

### ISSUE THREAD

**Issue by BondingX** [FlorianWoelki/obsidian-icon-folder#49]
all icons are shown as "Ri%%%%line", and there are obsidian error reports shown as "seems that you do not have an icon pack installed"

**Comment by FlorianWoelki** [comment]
If the migration script did not correctly work, you need to re-add the icons to your folders/icons.

**Comment by aulambda** [comment]
I'm getting the same issue, but I can't re-add icons, as the icon packs now show up as empty, even after re-downloading, and re-installing the app and re-downloading.
![Uploading 4B0B4209-32B6-41DF-8321-11B9D9FE8EAE.jpeg…]()

**Comment by aulambda** [comment]
I'm getting the same issue, but I can't re-add icons, as the icon packs now show up as empty, even after re-downloading, and re-installing the app and re-downloading.
![D340073E-5EE7-498B-85D2-FD55FD1C9D47](https://user-images.githubusercontent.com/11554939/160194299-1ff7222f-b3dc-4716-92df-ba2e30edc0b9.jpeg)

**Comment by Miaoyifei-mz** [comment]
@aulambda I'm getting the same issue too。

**Comment by FlorianWoelki** [comment]
Are there any issues in the console? Can you open up the console and show the output? If there is any.

**Comment by Cammagno** [comment]
same issue for me, solved by manually downloading the packs and adding all their icons to the predefined icon packs

**Comment by spasticginger** [comment]
I'm having the same issue.  I've uninstalled & reinstalled the plugin, added the icon packs back in, but they all show '0' icons, and clicking on what I'm guessing is an edit button crashes Obsidian.  😕

**Comment by FlorianWoelki** [comment]
> I'm having the same issue.  I've uninstalled & reinstalled the plugin, added the icon packs back in, but they all show '0' icons, and clicking on what I'm guessing is an edit button crashes Obsidian.  😕

I need more information on that. Could you create specific reproduction steps and maybe the error on why Obsidian crashes?

**Comment by spasticginger** [comment]
> > I'm having the same issue.  I've uninstalled & reinstalled the plugin, added the icon packs back in, but they all show '0' icons, and clicking on what I'm guessing is an edit button crashes Obsidian.  😕
> 
> I need more information on that. Could you create specific reproduction steps and maybe the error on why Obsidian crashes?

After reinstalling...
- Opened the plug-in options
- Used the 'Browse' button to add a predefined pack
-nothing showed in the list- waited about 5-10 minutes in case something was happening in the background
- restarted Obsidian (the pack won't show in the list unstill restarted)
- now shows the packs as installed, but with 0 icons
-clicked on '+' button to see if anything would show or if I could add something
-Obsifian immediatelu closes without any error message

**I'm using the Android version of Obsidian

![Screenshot_20220327-090431.png](https://user-images.githubusercontent.com/22240867/160282802-c608ebfb-ec1f-4a38-8963-db978fad22da.png)

**Comment by FlorianWoelki** [comment]
> > > I'm having the same issue.  I've uninstalled & reinstalled the plugin, added the icon packs back in, but they all show '0' icons, and clicking on what I'm guessing is an edit button crashes Obsidian.  😕
> > 
> > I need more information on that. Could you create specific reproduction steps and maybe the error on why Obsidian crashes?
> 
> After reinstalling...
> - Opened the plug-in options
> - Used the 'Browse' button to add a predefined pack
> -nothing showed in the list- waited about 5-10 minutes in case something was happening in the background
> - restarted Obsidian (the pack won't show in the list unstill restarted)
> - now shows the packs as installed, but with 0 icons
> -clicked on '+' button to see if anything would show or if I could add something
> -Obsifian immediatelu closes without any error message
> 
> **I'm using the Android version of Obsidian
> 
> ![Screenshot_20220327-090431.png](https://user-images.githubusercontent.com/22240867/160282802-c608ebfb-ec1f-4a38-8963-db978fad22da.png)

Awesome thanks. I could reproduce on my mobile phone as well. At the moment it is downloading the icon packs from the web. Maybe this is the issue. I'll further investigate it.

**Comment by FlorianWoelki** [comment]
Moving the issue of downloading icon packs on mobile to #55
