### ISSUE TITLE
Allowing to disable arrowback icon in footnote

### ISSUE THREAD

**Issue by l2eused** [FlorianWoelki/obsidian-icon-folder#499]
**Is your feature request related to a problem? Please describe.**
Yes, when enable this plugin, it will change from line arrow to icon arrow that not option to enable/disable it.

**Describe the solution you'd like**
Allow to use old style arrow

**Additional context**
this is when I enable plugin
![Obsidian_k7FSP4LIAs](https://github.com/FlorianWoelki/obsidian-iconize/assets/94383254/62aad23c-db7a-4184-b5ad-b6f7c2e38b29)
and this one when I disable plugin (original obsidian style)
![Obsidian_1lDGVAEsLB](https://github.com/FlorianWoelki/obsidian-iconize/assets/94383254/243a1a73-beaa-4da6-9b4b-ccbc26e11a22)

**Comment by AkikoAkaki** [comment]
Hey how did you solve this issue or is it appearing again?
