### ISSUE TITLE
Recently used icons in chronological order of last use

### ISSUE THREAD

**Issue by Cammagno** [FlorianWoelki/obsidian-icon-folder#50]
Now they are aranged in chronological order of first use (meaning: the first one in the list is the last that has been used for the first time).
I'd like them in chronological order of last use (meaning: the first one in the list should be the last that has been used).

Example
I use for the first time icon A, then B, then C, then again A

Now, I have them listed as C, B, A (and if my limit is set to n=2, A is not listed at all)
I'd like to have them listed as A, C, B (so that the last n used icons are always in the list)

**Comment by FlorianWoelki** [comment]
I personally think that this feature is really specific and it would be too much just for one user. If there are further requests like this, I will consider implementing an option for that.

**Comment by Cammagno** [comment]
> I personally think that this feature is really specific and it would be too much just for one user. If there are further requests like this, I will consider implementing an option for that.

Sure, if I'm the only person interested in this, or if there are few of us, no reason to bother!

Anyway, just for the sake of argument, the one I'm asking for is - as far as I know - the default behavior of all the most common apps, including Windows, Office and so on: the last used files are always in reverse order of their last use, not of their first use.

**Comment by FlorianWoelki** [comment]
Ok that makes actually sense. I will reverse the order!
