### ISSUE TITLE
Allow Different Icon Colors For Individual Folders/Files

### ISSUE THREAD

**Issue by Trikzon** [FlorianWoelki/obsidian-icon-folder#51]
**Is your feature request related to a problem? Please describe.**
Right now, as far as I can find, I can only change every icon's color to a single color.

**Describe the solution you'd like**
The ability to choose the icon's color in the "Change Icon" menu or new menu for each folder/file individually.

**Describe alternatives you've considered**
Instead of individually choosing the colors, colors could be set in the plugin's settings page through regex selectors. That way any note with certain characters in its name could be the same colors (or even based on note tags?)

**Comment by FlorianWoelki** [comment]
This functionality is now available in the [newest release](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.2.0) :)
