### ISSUE TITLE
Twemoji is not listed as one of the icon packs available for downloading

### ISSUE THREAD

**Issue by owldown** [FlorianWoelki/obsidian-icon-folder#53]
Only the 3 font-awesome and the one remix packs are listed.

**Comment by FlorianWoelki** [comment]
That is correct. I may refactor the readme file. Right now, the Twemoji functionality is directly implemented and there is no need to download it.

**Comment by owldown** [comment]
Oh interesting. I followed the directions on my Mac and typed an emoji but got nothing as a result. Maybe I should have restarted Obsidian after installing the plugin.

**Comment by owldown** [comment]
Okay, restarting Obsidian did allow it to work correctly, but I agree that the README is confusing, in saying that it can be downloaded. I should know by now that Obsidian does not work correctly after installing a new plugin until it is restarted.

**Comment by FlorianWoelki** [comment]
> Okay, restarting Obsidian did allow it to work correctly, but I agree that the README is confusing, in saying that it can be downloaded. I should know by now that Obsidian does not work correctly after installing a new plugin until it is restarted. 

Alright thank you for your feedback. I'll look into the problem with the restarting and change the readme.
