### ISSUE TITLE
icon pack download does not work on mobile devices

### ISSUE THREAD

**Issue by kruemel746** [FlorianWoelki/obsidian-icon-folder#55]
When adding icon packs on mobile devices (actual ios as well as android) nothing seems to happen. After restarting obsidan, only an empty folder of the icon pack appears.

Tried the default folder as well as ".obsidian/icons"

Thanks a lot!

**Comment by kruemel746** [comment]
Don´t know if this helps, but it seems like mobile obsidian app / the plugin has difficulties to access the ".obsidian" - folder while importing icons packs and syncing custom icons.

Even with successfully synced icons, it deletes icons when syncing sometimes later. Both in the default subfolder as well as in ".obsidian/icons".

Perhaps it is a more general problem?!

**Comment by rbutera** [comment]
same issue here

I've also noticed that obsidian struggles to sync commnuity plugin settings properly. I have to manually reconfigure community plugins after install. Is this your experience also, @kruemel746 ?

**Comment by FlorianWoelki** [comment]
I am still investing this issue. Seems like obsidian sync has problems with plugin data syncing.

**Comment by kruemel746** [comment]
@rbutera 
Regarding the syncronization, I have experienced that first all icons are distributed to the end devices. During the next synchronization, some icons are deleted again. This was the case in the default subfolder as well as in ".obsidian/icons". This was always reproducible for me when an iOS device was involved.

The plugin settings (folder path and assignment of icons to folders) were synchronized without problems.

@FlorianWoelki 
Thanks a lot for your effort! :-)

**Comment by spasticginger** [comment]
> Don´t know if this helps, but it seems like mobile obsidian app / the plugin has difficulties to access the ".obsidian" - folder while importing icons packs and syncing custom icons.
> 
> Even with successfully synced icons, it deletes icons when syncing sometimes later. Both in the default subfolder as well as in ".obsidian/icons".
> 
> Perhaps it is a more general problem?!

I think the Icon Shortcodes plugin is facing a [similar issue](https://github.com/aidenlx/obsidian-icon-shortcodes/issues/35) and also utilizes the .obsidian/icons folder.

**Comment by Oblique82** [comment]
Is there any way I can restore my settings from previously if there were wiped by this? I use obsidian cloud - are they in there somewhere?

**Comment by kruemel746** [comment]
How about just moving the icons to the Vault? Unfortunately the folder path can't be outside of ".obsidian" at the moment.

**Comment by FlorianWoelki** [comment]
Should be fixed with the newest release.

**Comment by Cateroo** [comment]
I installed the plugin on my desktop and mobile yesterday. I seen to be having this problem on my Android mobile still - is there something I need to do for the fix to function?
