### ISSUE TITLE
Separate File & Folder Icon Colors

### ISSUE THREAD

**Issue by ChristinWhite** [FlorianWoelki/obsidian-icon-folder#57]
In some themes, especially the more minimalistic themes like Minimal, there isn't always a very clear differentiation between files and folders, particularly when you put an icon between the disclosure arrow and the file text. It would be nice to be able to change the color of all folders and all files separately, either through a setting or at least with a different class we could create a snippet to use. 

<img width="291" alt="CleanShot 2022-04-04 at 20 28 30@2x" src="https://user-images.githubusercontent.com/1746405/161673134-50cb979b-f592-4d37-91d6-cd493ab51b23.png">

Given similar titles it's probably worth noting that this is different from #51 which is requesting specific overrides of individual icons. If both features were implemented it would make sense to have #51 take priority as the more specific classification.

**Comment by FlorianWoelki** [comment]
This functionality is now available in the [newest release](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.2.0) :)

**Comment by ChristinWhite** [comment]
Just wanted to say thanks Florian!

**Comment by FlorianWoelki** [comment]
> Just wanted to say thanks Florian!

Sure no problem! :)
