### ISSUE TITLE
Always Use Icon for Specified Folder Name (like 'Attachments')

### ISSUE THREAD

**Issue by ChristinWhite** [FlorianWoelki/obsidian-icon-folder#58]
One thing I find myself doing over and over is applying the same icon to individual instances of the same files (`Dashboard`, `Kanban`, `MOC`) or folders like `Attachments` if you don't use one attachment folder for the whole vault. It would be awesome is I could specify a rule based on the file and folder name and Icon Folder would apply the same icon to each instance of it. 

Assuming it wouldn't bog performance down it would be great if it could support regex or fuzzy matching for things like `Topic A MOC` and `Topic B MOC`.

**Comment by FlorianWoelki** [comment]
I think the best way is to create this functionality with fuzzy matching. Regex would be too much for the "standard" user :D

**Comment by ChristinWhite** [comment]
I agree, I just wasn't sure which of the two would make more work for you.

**Comment by FlorianWoelki** [comment]
The latest commits should add the functionality of adding custom rules. It works with Regex, or a simple string includes functionality. I'll continue testing the functionality and release it asap.

**Comment by FlorianWoelki** [comment]
It should now be possible with the newest release to add custom rules. :)
