### ISSUE TITLE
Icon Packs vanishing from Icon Folder Plugin Settings.

### ISSUE THREAD

**Issue by aknight2015** [FlorianWoelki/obsidian-icon-folder#61]
I'm running Obsidian on Debian 11. I've got the most up to date version of the plugin. For some reason when I close Obsidian and restart it all the icon packs I loaded previously are totally gone. I go to put an icon on a folder and it says "Create and icon pack", so I go into options and any of the icons I had previously loaded are gone. I went to look in the folder .obsidian/plugins/obsidian-icon-folder/icons and obsidian-icon-folder isn't even there. I click on the save option hoping it'll recreate the directory. Nope. Nothing. I create it manually, the plugin doesn't use it. The really weird part is that all the icons I used on the folders in the vault show up just fine. They load up with no issue, as in they appear in Obsidian explorer.

**Comment by FlorianWoelki** [comment]
Thank you for your bug report. I cannot test it with Debian. Is it possible that is a problem with Obsidian and Debian itself?
