### ISSUE TITLE
Default icon, and multi-level subfolder inheritance icon

### ISSUE THREAD

**Issue by MugenLee** [FlorianWoelki/obsidian-icon-folder#62]
**Is your feature request related to a problem? Please describe.**
This requirement is mainly because when I use Obsidian version 0.14.6 and iconfolder plugin version 1.1.4, I cannot customize an icon that takes effect by default for all folders
Although you can inherit the icon, it seems to be only valid for the first-level subfolder, and the second-level subfolder will not take effect, so the setting will be very troublesome, and it will not take effect for the newly created folder.

**Describe the solution you'd like**
I can think of 2 ways
1. You can customize an icon that is valid for all folders, no matter where it is, or create a new folder

2. The inherit icon is valid for all depth folders under a folder, and it is also valid for new ones

exist
On the basis of 1 and 2, you can freely modify the icon for a certain folder

If possible, I would like to be able to distinguish between the icon of the settings folder and the icon of the file

Because when using the inheritance function, files and folders will be added with the same icon, and I want folders and files to use different icons

**Describe alternatives you've considered**
Please refer to my thoughts above

**Additional context**
Please refer to my thoughts above
I think this is just a necessity. After all, many people want icons for DIY folders, but they don't want some folders to have icons, while others don't have icons.

Above, if you have any questions, please feel free to communicate

We are expecting a reply
@FlorianWoelki

**Comment by FlorianWoelki** [comment]
Hey,

thank you for your detailed request. I will discuss the inheritance problem at issue #63 

Furthermore, is your request related to #58 ?

**Comment by MugenLee** [comment]
> Hey,
> 
> Thank you for your detailed request. I will discuss the inheritance problem in issue #63
> 
> Furthermore, is your request related to #58 ?

yes it like #58 

Simply say it ,than
1. The folder icon and file icon can be set to different default icons

2. The folder or file with the default icon has been set, you can change the icon

3. The newly created folder or file can inherit the default icon

**Comment by FlorianWoelki** [comment]
You can check out the newest release. There is now the ability to automatically add custom rules for adding icons based on a regex or string.

**Comment by MugenLee** [comment]
> 您可以查看最新版本。现在可以根据正则表达式或字符串自动添加自定义规则以添加图标。



> 您可以查看最新版本。现在可以根据正则表达式或字符串自动添加自定义规则以添加图标。



> You can check out the newest release. There is now the ability to automatically add custom rules for adding icons based on a regex or string.

OK thx for your works~
