### ISSUE TITLE
Inheritance broken?

### ISSUE THREAD

**Issue by nousernameavailableanymore** [FlorianWoelki/obsidian-icon-folder#63]
Currently using version 1.1.4 of Icon Folder.
In previous versions, "inherit icon" would inherit that icon to ALL notes below that folder (which is what one would expect of a function called "inherit").

In the latest version it only inherits the icon one level down, to all notes and folders.

Is there any way to
1. inherit ONLY to notes
2. inherit to ALL notes within a folder (not just one level down)

Edit:
Just reverted back to 1.1.3 and it fixes both issues.
ALL notes in the folder interit the icon and ONLY notes do.

**Comment by FlorianWoelki** [comment]
Yeah it is correct that in 1.1.3 it inherits all the way down to all the files. However, I wasn't quite sure, if it is right.

Because let's assume the following scenario:
I am going to add inheritance to one folder, and all files at the top level will have this inheritance icon. In addition, I have another subfolder and want to add inheritance to this subfolder. Then we have a problem of inheritance. Therefore, my idea was only to have the top-level inherit the icon.

What do you think of adding a setting for changing this behaviour?

**Comment by nousernameavailableanymore** [comment]
At least a setting would be great (please also one to NOT apply the icon to folders but only notes, as was also the case in the 1.1.3).

However, wouldnt it be logical that if the subfolder (or rather the notes in the subfolder) is supposed to receive a different icon, that one would simply right-click on the subfolder and select "inherit icon".
So the inheritance of the subfolder would overwrite the inheritance of the upper folder.
Thats the usual way of doing things (for example group policies in AD and similar).

Also, in 1.1.3, this seems to have worked exactly like that.
When right-clicking on a folder, only the folder, where the inheritance was configured shows "remove inherit icon".
When clicking on a subfolder, the option "inherit icon" to overwrite the icons in that subfolder is still available (as it should be).

So from my point of view its pretty clear and I would do it the same way as is common everywhere else (as mentioned above, for example in AD): inheritance goes all the way down to the lowest subfolder / notes in that subfolder and more specific inheritance (ie the ones in / for subfolders) overwrites the less specific inheritance of the upper folder.

**Comment by FlorianWoelki** [comment]
> At least a setting would be great (please also one to NOT apply the icon to folders but only notes, as was also the case in the 1.1.3).
> 
> 
> 
> However, wouldnt it be logical that if the subfolder (or rather the notes in the subfolder) is supposed to receive a different icon, that one would simply right-click on the subfolder and select "inherit icon".
> 
> So the inheritance of the subfolder would overwrite the inheritance of the upper folder.
> 
> Thats the usual way of doing things (for example group policies in AD and similar).
> 
> 
> 
> Also, in 1.1.3, this seems to have worked exactly like that.
> 
> When right-clicking on a folder, only the folder, where the inheritance was configured shows "remove inherit icon".
> 
> When clicking on a subfolder, the option "inherit icon" to overwrite the icons in that subfolder is still available (as it should be).
> 
> 
> 
> So from my point of view its pretty clear and I would do it the same way as is common everywhere else (as mentioned above, for example in AD): inheritance goes all the way down to the lowest subfolder / notes in that subfolder and more specific inheritance (ie the ones in / for subfolders) overwrites the less specific inheritance of the upper folder.

Thank you for your detailed explanation. I'll revert my changes back to the original functionality, without an additional option unless there is some need for other users.
