### ISSUE TITLE
Sync Icons w across devices

### ISSUE THREAD

**Issue by melmaninga** [FlorianWoelki/obsidian-icon-folder#64]
**Describe the bug**
Folder Icons set in Desktop App do not appear in Vault synced to Mobile App

**To Reproduce**
Steps to reproduce the behaviour:
Set Icons in desktop app.
Go iPad and sync vault via Obsidian Sync (for first time and resync)

**Expected behavior**
Icons to appear as previously set on other devices

**Comment by FlorianWoelki** [comment]
Please checkout the readme regarding sync issues and #52 for more information.
