### ISSUE TITLE
All Icons preview does not show all icons available

### ISSUE THREAD

**Issue by Boerner1337** [FlorianWoelki/obsidian-icon-folder#65]
Hey Florian, 

I started using your plugin and found that when adding icons to notes or folders by right clicking the note or folder and select "# Change Icon" in the popping up preview window not all available icons are displayed. 
Only when searching specifially for the icon I can see it. 
Is there a reason for the limitation of displaying only a handful icons? Or is there a setting I need to change I over read?

(I am using the remixicon pack downloaded directly in the plugin with those some 2000 icons) 

Thanks,
Kev

**Comment by FlorianWoelki** [comment]
Hey,

thank you for your question. This is a feature, not a bug :D The reason being is that loading all the icons is taking too long for obsidian to process, and there is no modal lazy loading functionality yet.

So there is a fixed limit to the preview icons, because of the loading performance.
