### ISSUE TITLE
Rules problem (everything doesn't apply) 

### ISSUE THREAD

**Issue by Mara-Li** [FlorianWoelki/obsidian-icon-folder#68]
**Describe the bug**
- Everything rules doesn't apply on configured folder. 
![image](https://user-images.githubusercontent.com/30244939/168469750-7440fcee-ce53-4874-9798-9e64fe564a2a.png)
Behavior on folder : 
![image](https://user-images.githubusercontent.com/30244939/168469772-337107fd-266c-4200-a2f6-23123b3cae65.png)
(No icons)
Behavior on file : 
![image](https://user-images.githubusercontent.com/30244939/168469788-e381161b-227d-4ca7-98cb-43cc78335f4a.png)
Icon doesn't are applied, double icon based on another rules : `\.md$`, configured on file.

Another bug, based on rule : 
![image](https://user-images.githubusercontent.com/30244939/168469832-136326c4-36f6-46f9-9a66-c2d7cca79e76.png)
![image](https://user-images.githubusercontent.com/30244939/168469849-d0aced4f-1b81-4a11-aa61-2f5278ebde49.png)
For these, force the application using `everything` work... Only on opened folder, and removed when reloading Obsidian. 

**To Reproduce**
Configure the rules as above. Try with : 
- Png image 
- Folder + File with same name

**Expected behavior**
Icon added

**Comment by Mara-Li** [comment]
Console : 
![image](https://user-images.githubusercontent.com/30244939/168470331-05060d4b-3708-49d3-b19e-577a07631f2b.png)

**Comment by Mara-Li** [comment]
As I invastigate, I think it's an issue with rule order.
My suggestion : Adding an option in settings to reordering rules!

**Comment by FlorianWoelki** [comment]
The first issue should be solved now. Just recreate the rule and everything should work fine.

However, I need to investigate the second issue with the images. Is this a plugin or how can I reproduce it?

**Comment by Mara-Li** [comment]
For the image, I can't know why I have this. But ! I cleaned *all* my rules and now, it works.

**Comment by Mara-Li** [comment]
Thanks for the quick update btw

**Comment by Mara-Li** [comment]
Pretty frustrating : cleaned settings, adding rules, reloading Obsidian => Custom rules doesn't apply for some folder. 
I updated the plugin ...

**Comment by FlorianWoelki** [comment]
Maybe there is some interference with other plugins?

**Comment by Mara-Li** [comment]
I don't think so. The only plugin I have that touch folder is folder note, and removing doesn't change anything... I will try with disabling all plugin to see !

**Comment by Mara-Li** [comment]
Yes, reload Obsidian, remove every plugin (and only keep Icon folder) doesn't change anything with my problem.

**Comment by Mara-Li** [comment]
OKAY 
I found it !
If adding manually a specific rule on *folder* every custom rule that can apply in this folder broke, even though there haven't specific rule.

**Comment by FlorianWoelki** [comment]
Ok, so the order is important. Does it make sense to let the user specify the prioritization of a rule?

**Comment by Mara-Li** [comment]
I think it can be a good idea. 
Like "override specific" "override inheritance" ?

**Comment by FlorianWoelki** [comment]
I think this would be too confusing. How about just moving the rules up and down? So that the first rule has the most prioritization and always comes first?

**Comment by Mara-Li** [comment]
Yeah, good idea.
But I think the problem is maybe around the way regex are handled. For example, I set "truc" as a custom rule.
Truc is a valid regex, so it never catches the error, and it returns false when testing the rule.

**Comment by Mara-Li** [comment]
Okay, I found the error. In fact, I was my fault. I messed up with `true`, `false` and `!` ;')

**Comment by FlorianWoelki** [comment]
:D nice to know. Feel free to close the issues, when everything is solved.

**Comment by Mara-Li** [comment]
I will made a pull request with the fix !

**Comment by FlorianWoelki** [comment]
I will keep track of the priorization order in #71.

**Comment by Mara-Li** [comment]
Okay ! I close the issue, as I correct in the PR.
