### ISSUE TITLE
Double inheritance

### ISSUE THREAD

**Issue by Mara-Li** [FlorianWoelki/obsidian-icon-folder#70]
**Describe the bug**
The plugin will add two icons when using inheritance in a folder who already have an inheritance. 
Eg something like this : 
```
folder A => Inherit icon
  folder B => Set inherit icon
     file => Will inherit from A & B
```

**To Reproduce**
1. Create a folder A
2. Create a folder B in folder A
3. Set inherit icon in folder A and B
4. Reload the app 

**Expected behavior**
The icon chooses must be from folder B

**Screenshots**
![image](https://user-images.githubusercontent.com/30244939/168478545-ea0fb0c5-ebe5-4285-be21-46a52c46f0e0.png)

**Additional context**
/

**Comment by aomader** [comment]
Using version 1.4.3, this is not resolved for me:
![image](https://user-images.githubusercontent.com/23704/204274211-ad8f9975-6397-4970-b881-3d06eff4a414.png)

**Comment by aomader** [comment]
Sure, here you go:
```
{
  "settings": {
    "migrated": true,
    "iconPacksPath": ".obsidian/plugins/obsidian-icon-folder/icons",
    "fontSize": 16,
    "iconColor": null,
    "recentlyUsedIcons": [
      "FasRepeat",
      "💡",
      "FasKey",
      "FasHashtag",
      "IbTrayStacked"
    ],
    "recentlyUsedIconsSize": 5,
    "rules": [],
    "extraMargin": {
      "top": 0,
      "right": 4,
      "bottom": 0,
      "left": 0
    }
  },
  "Journal": {
    "iconName": "📔",
    "inheritanceIcon": "FasHashtag"
  },
  "Journal/2022": {
    "iconName": "FasHashtag",
    "inheritanceIcon": "FasHashtag"
  },
  "Journal/2022/11": {
    "iconName": "FasHashtag",
    "inheritanceIcon": "🗒"
  }
}
```
