### ISSUE TITLE
Search issues when Icon Folder is enabled

### ISSUE THREAD

**Issue by fdr95** [FlorianWoelki/obsidian-icon-folder#72]
When the plugin is enabled Obsidian cannot properly search through the folders. It only finds some results and then keep "loading" indefinitely. I also tried enabling the others plugin one by one and in different combinations, but I found this issue only when Icon Folder was enabled. 

Obsidian version = 0.14.6
Icon Folder version = 1.2.1

**Comment by FlorianWoelki** [comment]
Should be fixed for now with the newest release.
