### ISSUE TITLE
Support custom .obsidian config directory

### ISSUE THREAD

**Issue by r4zzz4k** [FlorianWoelki/obsidian-icon-folder#73]
**Describe the bug**
Recent version of Obsidian supports changing config directory from `.obsidian` to some custom value. For example, this is useful if one wants to have different plugin set for desktop and mobile apps, or in case synchronization software doesn't support hidden directories at all. Currently, the plugin prepends icon pack location with `.obsidian/` unconditionally. It should access new [`Vault.configDir`](https://github.com/obsidianmd/obsidian-api/blob/9bb30633586c6649474b2affdf5b87efdd86498f/obsidian.d.ts#L3331-L3336) field if it's present, falling back to default `.obsidian` value if that's not present. Either that, or it should allow to store icons outside of config directory, which may be beneficial in the mentioned scenario with different directories for mobile and desktop: icon packs would most probably be the same, so without this users would have to setup symlink.

**To Reproduce**
1. Open Obsidian
2. Copy your `.obsidian` directory as `.obsidian.desktop`.
3. Open Settings
4. Open 'About' screen
5. Put `.obsidian.desktop` in "Override config folder".
6. Close Obsidian
7. Delete `.obsidian` directory.
8. Open Obsidian again.
Note that the old directory is back again, the plugin created an empty folder for the icon packs, and there are alerts about missing icons.

**Expected behavior**
Plugin should either search for icons in new config directory or allow to set the directory outside of `.obsidian`.

**Comment by r4zzz4k** [comment]
Thank you, @FlorianWoelki!

I've installed an update to check it. This fix seems to interpret configuration differently from the previous version. The default value was `plugins/obsidian-icon-folder/icons`, and previous version was checking for `.obsidian/plugins/obsidian-icon-folder/icons`, and current one expects a different folder. So this is a breaking change without any additional migration. As soon as you install an update, it pops up with multiple notifications of missing icons, and users have to change the config to prepend `.obsidian` if they don't want to relocate anything in file system.

Personally I'm grateful for the ability to move icon packs elsewhere, and I'm okay with migrating them myself. It may be a bit unexpected for other users though. So it might be reasonable to at least add some warning in the readme. Though this is up to you of course :)

Thank you for the fix, and thank you for this useful plugin!

**Comment by FlorianWoelki** [comment]
> Thank you, @FlorianWoelki!
> 
> 
> 
> I've installed an update to check it. This fix seems to interpret configuration differently from the previous version. The default value was `plugins/obsidian-icon-folder/icons`, and previous version was checking for `.obsidian/plugins/obsidian-icon-folder/icons`, and current one expects a different folder. So this is a breaking change without any additional migration. As soon as you install an update, it pops up with multiple notifications of missing icons, and users have to change the config to prepend `.obsidian` if they don't want to relocate anything in file system.
> 
> 
> 
> Personally I'm grateful for the ability to move icon packs elsewhere, and I'm okay with migrating them myself. It may be a bit unexpected for other users though. So it might be reasonable to at least add some warning in the readme. Though this is up to you of course :)
> 
> 
> 
> Thank you for the fix, and thank you for this useful plugin!

Sure thanks! There is a note in the release guide.

**Comment by FlorianWoelki** [comment]
No worries :D but I'll write that in the README file tomorrow as well. Thanks!
