### ISSUE TITLE
Icons not applying to "Drag to Rearrange" Icon

### ISSUE THREAD

**Issue by Aithr-13** [FlorianWoelki/obsidian-icon-folder#75]
**Describe the bug**
Icons do not seem to be applying to the portion of the window that allows them to be arranged.

**To Reproduce**
1. Set an icon to a note.
2. Drag that note to the sidebar.
3. Icon remains unchanged in sidebar.

**Screenshots**
<img width="189" alt="image" src="https://user-images.githubusercontent.com/53221646/171684712-efc902f8-eb25-49eb-a86a-7a1dcfd5e944.png">

**Comment by FlorianWoelki** [comment]
Thank you for reporting your issue!
What do you mean by dragging in the sidebar?

**Comment by Aithr-13** [comment]
When dragging to any of the contextual sidebars (to the left or right side of Obsidian pane) the Icon doesn't apply. Pictured in my initial screenshot is a file titled QuickAccess which has been pinned in to the left sidebar just below where the file shows in the File explorer. This area is div.workspace_tabs in Obsidian's HTML structure.
As you can see, the icon shown in the file explorer for QuickAccess differs from the file's icon when pinned (shown underneath)

I found a code snippet on the obsidian forums that I used to produce the following CSS to resolve this issue:
`
/* Setting the default icon to not show */
.workspace-tab-header[aria-label^="QuickAccess"]
> .workspace-tab-header-inner
> .workspace-tab-header-inner-icon
> .document{
    display: none;
}

/* adding the new icon via SVG and setting some parameters for it */
.workspace-tab-header[aria-label^="QuickAccess"]
> .workspace-tab-header-inner
> .workspace-tab-header-inner-icon{
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='none' d='M0 0h24v24H0z'/%3E%3Cpath d='M19 22H5a3 3 0 0 1-3-3V3a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v12h4v4a3 3 0 0 1-3 3zm-1-5v2a1 1 0 0 0 2 0v-2h-2zm-2 3V4H4v15a1 1 0 0 0 1 1h11zM6 7h8v2H6V7zm0 4h8v2H6v-2zm0 4h5v2H6v-2z' fill='rgba(133,146,137,1)'/%3E%3C/svg%3E");
    background-size: 17px 17px; 
    transform: translate(0px, 5px); /* to position the icon */
    background-repeat: no-repeat;
    display: inline-block;
    height: 17px;
    width: 17px;
    margin: -4px 2px 0 0;
}

/* Setting the hover behavior to change the color to match my theme */
.workspace-tab-header[aria-label^="QuickAccess"]
> .workspace-tab-header-inner
> .workspace-tab-header-inner-icon:hover{
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='none' d='M0 0h24v24H0z'/%3E%3Cpath d='M19 22H5a3 3 0 0 1-3-3V3a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v12h4v4a3 3 0 0 1-3 3zm-1-5v2a1 1 0 0 0 2 0v-2h-2zm-2 3V4H4v15a1 1 0 0 0 1 1h11zM6 7h8v2H6V7zm0 4h8v2H6v-2zm0 4h5v2H6v-2z' fill='rgba(211,198,170,1)'/%3E%3C/svg%3E");
    background-size: 17px 17px; /* adopt this to your file tree font height */
    transform: translate(0px, 5px); /* to position the icon */
    background-repeat: no-repeat;
    display: inline-block;
    height: 17px;
    width: 17px;
    margin: -4px 2px 0 0;
}
`

With that said, this also doesn't change the icon for the file when it's open in the workspace view header, which is defined as `<div class="view-header"><div class="view-header-icon" aria-label="Drag to rearrange">` 
in Obsidian's HTML structure. Judging by the name - I'm not sure if this is actually even something that you can set on a per-item basis, as it looks like modifying this icon would change it for every document which is loaded, not just the one which was selected. See below:
<img width="810" alt="Screen Shot 2022-06-15 at 12 16 31 PM" src="https://user-images.githubusercontent.com/53221646/173877515-3a67bc65-9289-4db3-90fb-9b31b1a57000.png">

With all this said - I'm not sure this was originally intended functionality for this plugin, or if I'm assuming it should have capabilities it shouldn't. I'm not really an HTML/CSS guy, so I'm not sure how you would go about rectifying these in the framework of the plugin.

**Comment by FlorianWoelki** [comment]
Should be added with [version 1.3.3](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.3.3).
