### ISSUE TITLE
Can't set independent default icons for folders and files

### ISSUE THREAD

**Issue by keathmilligan** [FlorianWoelki/obsidian-icon-folder#77]
**Describe the bug**
Regex icon rules for folders and icons conflict with one another making it impossible to set independent default icons for folders vs. files.

**To Reproduce**
1. Go to settings
2. Create one icon rule `.*` for folders.
3. Create another rule (also `.*`) with a different icon to match files.
4. Note that only one or the other will work.

**Expected behavior**
Should be able to set independent rules for files and folders.

**Additional context**
Changing the regex to something slightly different like `.+` doesn't help - any overlapping matches cause the conflict.

**Comment by FlorianWoelki** [comment]
Did you change the type as well?

For example:
![image](https://user-images.githubusercontent.com/20746070/173757412-af23686d-c6fb-4caf-9263-4c7fc9f3f20f.png)

Gives me the following result:
![image](https://user-images.githubusercontent.com/20746070/173757457-f654aa81-2c0e-4113-babf-c0cd59dc1e9c.png)

**Comment by keathmilligan** [comment]
Yes, and when I click one, it causes the other to revert. Here is a gif of what I see:
![foldericons](https://user-images.githubusercontent.com/2936304/173889876-aa0f741a-1200-4383-89e8-4125333f97c3.gif)

I have found a work-around though - if I close and reopen the vault, the icons will be correct, but the incorrect behavior still remains if you try to change the settings.

**Comment by FlorianWoelki** [comment]
> Yes, and when I click one, it causes the other to revert. Here is a gif of what I see: ![foldericons](https://user-images.githubusercontent.com/2936304/173889876-aa0f741a-1200-4383-89e8-4125333f97c3.gif) [ ](https://user-images.githubusercontent.com/2936304/173889876-aa0f741a-1200-4383-89e8-4125333f97c3.gif) ![foldericons](https://user-images.githubusercontent.com/2936304/173889876-aa0f741a-1200-4383-89e8-4125333f97c3.gif) [ ](https://user-images.githubusercontent.com/2936304/173889876-aa0f741a-1200-4383-89e8-4125333f97c3.gif)
> 
> I have found a work-around though - if I close and reopen the vault, the icons will be correct, but the incorrect behavior still remains if you try to change the settings.

Ah ok got it! Thank you for the gif. That helped me a lot.
I will start fixing this issue asap.

**Comment by FlorianWoelki** [comment]
This issue should hopefully be resolved with the newest version v1.2.4. Thanks for reporting again.
