### ISSUE TITLE
Icon pack broke the plugin if user download icon too quickly

### ISSUE THREAD

**Issue by Mara-Li** [FlorianWoelki/obsidian-icon-folder#78]
**Describe the bug**
I spotted that, when I try to download remixicons right after font awesome solid, the plugin explode. Litteraly. I can doing any thing, and I must reload obsidian. Reload the plugin doesn't work either.

**To Reproduce**
1. Download font awesome solid.
2. Wait for the notice about downloading completed
3. Download Remixicons.
4. Boom.

**Expected behavior**
The plugin **should** wait before loading/downloading other pack.

**Screenshots**
/

**Additional context**
My assumption : the notice appear to quickly and the download is not completed. As a result, two icons pack are downloaded in parallels, causing the plugin to crash.

**Comment by FlorianWoelki** [comment]
Thank you for describing the issue. However, I cannot really reproduce this issue. The downloading of multiple icon packs, even at the same, should work because the actions are asynchronous. In addition, the notice always appears in the end, when a download is completed.

**Comment by Mara-Li** [comment]
Maybe it's because my vault is on Google drive ?

**Comment by FlorianWoelki** [comment]
> Maybe it's because my vault is on Google drive ?

That could be the case. Maybe Google drive cannot handle these many changes directly.

**Comment by Mara-Li** [comment]
I will close the issue : Because of that, I finished to use directly on google drive my vault. I created an save with Google drive, so my vault is just copied on google drive (because I need save, as Sync can't do that). 
Now, with this setup, the downloading work at 100%! I just noted that the number of icons can be incorrect (there is sometimes more icons indicated than it exists really in the folder)
