### ISSUE TITLE
Plugin causes search malfunction as of insider release 0.15

### ISSUE THREAD

**Issue by ryadaj** [FlorianWoelki/obsidian-icon-folder#79]
**Describe the bug**
When performing a search of any kind (by tag, by line, etc.) using the native search tool, no results are returned. Inspector points to this plugin as a cause. This is an issue only as of the new insider update (0.15).

**To Reproduce**
1. Go to 'Search'
2. Enter any keyword or tag which should return a result.
3. See that no results are returned.
4. See error in inspector (also attached)

**Expected behavior**
I expect normal search behavior.

**Screenshots**
Attached

**Additional context**
This was also an issue with the Icon Shortcodes plugin and was resolved: [see here](https://github.com/aidenlx/obsidian-icon-shortcodes/issues/51)

<img width="536" alt="Screen Shot 2022-06-15 at 08 13 09" src="https://user-images.githubusercontent.com/82765301/173824825-bcebec8c-0df9-4c9c-92c6-6fb86496a8b9.png">

**Comment by ryadaj** [comment]
I just noticed this also affects the local graph

**Comment by mtzfox** [comment]
I'm having this issue as well, came across it [here](https://forum.obsidian.md/t/search-results-sort-not-working-on-obsidian-v-0-14-15/38782/2).

**Comment by FlorianWoelki** [comment]
Thanks for reporting the issue. Unfortunately, I do not have any access to the insider builds and cannot fix it. We'll have to wait until I have access to it or the official version is released.

**Comment by ryadaj** [comment]
Just a quick update on my end.

The hotfix helped with search, but on updating the plugin, the icon packs needed to be reinstalled and a folder was created in my vault to contain the downloaded icons. This is not what happened previously.

<img width="1512" alt="Screen Shot 2022-06-16 at 15 08 29" src="https://user-images.githubusercontent.com/82765301/174146986-b94075f8-5a88-4d4b-a940-f09bea43db7b.png">
<img width="252" alt="Screen Shot 2022-06-16 at 15 08 25" src="https://user-images.githubusercontent.com/82765301/174146989-99dfbe5e-1463-43fe-8a02-beab5d882d97.png">
.

**Comment by FlorianWoelki** [comment]
> Just a quick update on my end.
> 
> 
> 
> The hotfix helped with search, but on updating the plugin, the icon packs needed to be reinstalled and a folder was created in my vault to contain the downloaded icons. This is not what happened previously.
> 
> 
> 
> <img width="1512" alt="Screen Shot 2022-06-16 at 15 08 29" src="https://user-images.githubusercontent.com/82765301/174146986-b94075f8-5a88-4d4b-a940-f09bea43db7b.png">
> 
> <img width="252" alt="Screen Shot 2022-06-16 at 15 08 25" src="https://user-images.githubusercontent.com/82765301/174146989-99dfbe5e-1463-43fe-8a02-beab5d882d97.png">
> 
> .

That's actually correct. I did write a migration guide in the release notes. However, to make it more clear, I'll also write it in the readme file tomorrow.

**Comment by ryadaj** [comment]
Ah sorry for missing that. Thank you :)

**Comment by Mara-Li** [comment]
Hello. My attent to fix the error with search is to just... Try and catch. 
See my PR in #69 
I just changed the manifest to keep my custom build away from yours. I can revert if you need (i will create a new branch for my side)

**Comment by FlorianWoelki** [comment]
> Hello. My attent to fix the error with search is to just... Try and catch. See my PR in #69 I just changed the manifest to keep my custom build away from yours. I can revert if you need (i will create a new branch for my side)

Thanks for doing that. Make sure that you create an extra PR based on that change, so I can review it.
