### ISSUE TITLE
Notice should include the plugin name regarding changing the icon set path

### ISSUE THREAD

**Issue by cfurrow** [FlorianWoelki/obsidian-icon-folder#82]
It seems after version v1.2.2, there's a notice that appears when this plugin is loaded:

![CleanShot 2022-06-18 at 09 13 31](https://user-images.githubusercontent.com/149965/174439325-0d4817fb-25a8-4c3b-a98d-99e9c9c1fcda.png)

> Due to a change in version v1.2.2, the obsidian folder changed. Please change it to not be directly in /plugins.

The problem is, the notice does not give the user any indication what plugin it's coming from, or where they should go to fix the issue. And it disappears within a few seconds.

**To Reproduce**
1. Install version v1.2.2 or v1.2.3
2. Edit the "Icon Packs folder path" and set it to "plugins/obsidian-icon-folder/icons"
3. Reload Obsidian, or close and re-open it
4. The error should appear in the top right corner of your Obsidian window as an Obsidian Notice

**Expected behavior**
I'd expect the Notice message to include the name of the plugin:

> [Obsidian Icon Folder] Due to a change in version v1.2.2, the obsidian folder changed. Please change it to not be directly in /plugins.

I'd also expect this same warning message to appear within the Obsidian Icon Folder settings window when the value for the "Icon Packs folder path" is "plugins/obsidian-icon-folder/icons"

Another valuable option may be to have a link in the Notice that could take the user to the plugin settings, if possible.
Another option would be to also include this message as a `console.error` message (or similar) so advanced users could see the message there.

If possible, can the Notice persist until dismissed? Or, perhaps set a timeout that's a bit longer. (the example below assumes the `timeout` argument is in milliseconds)

```typescript
// src/iconPackManager.ts

export const setPath = (newPath: string): void => {
  if (newPath === 'plugins/obsidian-icon-folder/icons') {
    newPath = '.obsidian/plugins/obsidian-icon-folder/icons';
    new Notice(
      'Due to a change in version v1.2.2, the obsidian folder changed. Please change it to not be directly in /plugins.', 5000
    );
  }

  path = newPath;
};

```

**Screenshots**
![CleanShot 2022-06-18 at 09 13 31](https://user-images.githubusercontent.com/149965/174439325-0d4817fb-25a8-4c3b-a98d-99e9c9c1fcda.png)

**Additional context**
_none_

**Comment by FlorianWoelki** [comment]
Should be solved with the latest Commit. Thanks again for the PR.

**Comment by cfurrow** [comment]
You bet! Thanks for the code review!
