### ISSUE TITLE
[Bug] Rules icon broken if parent folder have icon

### ISSUE THREAD

**Issue by Mara-Li** [FlorianWoelki/obsidian-icon-folder#86]
**Describe the bug**
The icons doesn't inherit from rules if the parent folder have an icon.

**To Reproduce**
1. Step an icon rules
2. Add an icon manually on the parent folder
3. Reload Obsidian

Also, forcing the rules to apply work... Until I reload Obsidian.

**Expected behavior**
The rules are applied. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30244939/174776942-af956e3e-36bb-4445-acb4-61546322fc2f.png)
![image](https://user-images.githubusercontent.com/30244939/174776977-4af2a9c8-b8bf-4b12-afbe-08619c3c8303.png)

**Additional context**

**Comment by Mara-Li** [comment]
I don't know how I managed that. I think you forget an await ? I edit a little my fork to include your update and the problem disappaear...

**Comment by FlorianWoelki** [comment]
Should be fixed with the latest commits.
