### ISSUE TITLE
[help] how should this box be filled in?

### ISSUE THREAD

**Issue by yslhzj** [FlorianWoelki/obsidian-icon-folder#88]
Excuse me, does this mean download directly from FontAwesome or Remixicons?

If so, how should this box be filled in? Thanks
![image](https://user-images.githubusercontent.com/29890756/175497142-fbf7b3d8-9946-4cd3-8dd6-6b3dedfecae5.png)

**Comment by FlorianWoelki** [comment]
The modal should be filled with icon packs that are predefined and can be downloaded directly. However, you already have the icon packs named after the downloaded ones. Therefore, I think you can feel free to delete the existing ones and redownload them.

**Comment by yslhzj** [comment]
According to your prompt, I reinstalled the plug-in. Found the reason is, may be before the network is not good, download the number of icon is 0, reinstall, re-download icon, on it, thank you.
![image](https://user-images.githubusercontent.com/29890756/175813808-ac64284f-2ec0-4a7a-8ade-aa63431f6fa0.png)

**Comment by FlorianWoelki** [comment]
Yeah, might be a network issue. Awesome that it works now!
