### ISSUE TITLE
Icon Folder Location

### ISSUE THREAD

**Issue by JimKnecht** [FlorianWoelki/obsidian-icon-folder#89]
Hi Just a warning/pre-apology I only have used the plugin for the first time for a few hours today so might have missed something...

**Is your feature request related to a problem? Please describe.**
A problem for me but not a bug. I have many vaults under one non vault folder. I tried to install the icons in a folder under that main nonvault folder so that I don't have to keep a whole copy of icons for every vault. I tried using "..\.ObsidianExtras\icons" so the .. would get to the parent nonvault folder. This worked and I made a new vault put in that path but it didn't seem to recognize the icons were installed and just showed a empty selection window when I tried to change the icon. I know the path was right because I renamed one of the downloaded libraries (FAS) and reinstalled it in the second vault and watched it all happen in the icon folder. I closed that second vault and the original vault.  I reloaded the original vault that initially worked but now that one just shows a blank selection pane like the second vault did. 

example of my folder structure 

NonVaultFolder
- .ObsidianExtras\icons   <- I'd like all the icons here instead of in each vault
- Vault1   <- Icons are currently here
- Vault2   <- and also here
- ValtEtc   <- and also here

**Describe the solution you'd like**
Allow us to define a single folder that multiple instances of the plugin can pull from so we don't have to keep duplicate libraries of icons.

**Describe alternatives you've considered**
Smashing my keyboard...decided against it.

**Additional context**
1) Another reason I'd like this feature besides just reducing duplicated files is that I often make all my CSS, Plugin, Etc changes to one vault then have a sync software copy that one vaults .obsidian folder to the other vaults (because obsidian also won't allow a config folder outside the vault...) and when doing this coping a lot of small files takes a long time.

2) Would it be possible for you to store the Folder: Icon part of data.json separately in each vault? As I mentioned above, I copy the .obsidian folder from one vault to all the others and am worried about the file growing really big and taking long to parse or conflicting if I have two folder or files with the same name in different vaults. 

Thanks for reading this and making the plugin.

**Comment by FlorianWoelki** [comment]
Thanks for the feature request. Maybe the issue is related to your path? Because it does not recognize an absolute path. Is there like any error in the console?
