### ISSUE TITLE
After updating icons are missing

### ISSUE THREAD

**Issue by mm47** [FlorianWoelki/obsidian-icon-folder#90]
**Describe the bug**
After the last update, many icons were missing. I downloaded the fontawesome and remix packs directly from the plugin configuration page, but some icons were still missing. Then I downloaded the packs from both websites and added the missing icons to a custom folder and assigned those to the folders and notes. Closing and opening Obsidian causes the custom icons to disappear being replaced with their code (e.g. "IoMovie2Fill") and a notification pop up warning about missing packages.

**To Reproduce**
1. Create custom icon folder in the .obsidian/icons directory;
2. Add icons to that folder;
3. Assign those custom icons to notes and folders;
4. Close and open Obsidian.

**Expected behavior**
Icons assigned from the custom folder shouldn't disappear after closing and reopening Obsidian.

**Comment by FlorianWoelki** [comment]
Thanks for reporting this issue. I cannot really reproduce it on my end.
Did you try to backup your icons and `reinstall` the plugin? Maybe that will fix some things. In addition, using the button to try to fix the icon pack might help as well.

**Comment by namtrah** [comment]
I have the same issue and it is horrendous (Remix losing over 3/4 after reinstall)

**Comment by FlorianWoelki** [comment]
I think this issue is solved in the newest version. I could not reproduce this issue locally. Make sure to normalize the icons whenever you create a custom directory with custom svg files in the icon packs folder.
