### ISSUE TITLE
Icons Disappearing

### ISSUE THREAD

**Issue by JFKTheory** [FlorianWoelki/obsidian-icon-folder#94]
**Describe the bug**
After adding an icon pack of my own (Font Awesome 6 Solid pro version) I noticed that the icons would seemingly randomly delete themselves. I can re-upload them and they stay, for a bit, but then continue to act strangely and would end up vanishing.

I noticed that this seemed to happen when I started using Obsidian Sync. I use it on my phone, and also as a collaborative vault with another person.

**To Reproduce**
1. Go to plugin settings
2. Upload your own icon pack
3. Use the icons on folders/notes
4. Open Sync log
5. Wait until Obsidian Sync tries to sync with other devices
6. See screenshot for what I'm seeing when the icons start to delete themselves

**Expected behavior**
I really only expected the icons to stay as is.

**Screenshots**
![Obsidian_KjKp4nYXVl](https://user-images.githubusercontent.com/47401806/178158635-1264c282-98bc-44de-9928-cc0682bf9610.png)

**Additional context**
This isn't only deleting icons I'm currently using, but it seems to delete them seemingly at random. Some of my currently used ones still work, others do not. If I fix the icon pack, nothing seems to happen on either my end or the other devices I'm sync'd with. I can re-upload and that fixes them for a time, but when it syncs, eventually, it seems to break all over again. If I do re-upload, I have to re-select the icons again.

**Comment by FlorianWoelki** [comment]
Please see this [section](https://github.com/FlorianWoelki/obsidian-icon-folder#sync-issue) for solving this issue.
