### ISSUE TITLE
Adding IconBrew set 

### ISSUE THREAD

**Issue by universvm** [FlorianWoelki/obsidian-icon-folder#95]
**Is your feature request related to a problem? Please describe.**
I'd like to add this icon pack: https://iconbrew.com/

**Describe the solution you'd like**
https://iconbrew.com/ integrated as an icon pack

**Describe alternatives you've considered**
n/a

**Comment by FlorianWoelki** [comment]
If a zip file can be downloaded that includes all the icons, I can add them to the predefined icon packs. However, right now, I don't see any option for that.

**Comment by universvm** [comment]
The author is in the process of adding a permanent link that will be updated periodically. (see https://twitter.com/leocastorina/status/1548651653926100993)

For the moment he sent this pack, though not sure how easy it is to integrate it:
[IconBrew icon pack.zip](https://github.com/FlorianWoelki/obsidian-icon-folder/files/9128536/IconBrew.icon.pack.zip)

**Comment by FlorianWoelki** [comment]
The icon brew icon pack is now available! It was released in version [1.3.0](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.3.0). Please keep me updated with the real link. Thank you for the suggestion!
