### ISSUE TITLE
Custom Icon Not Displaying Properly

### ISSUE THREAD

**Issue by GinoReiji** [FlorianWoelki/obsidian-icon-folder#98]
Before version 1.3.1, I couldn't change the folder icon size. I can change the size now, but some of the custom icons couldn't be displayed properly. 

The icons seems to display alright on the search box, for example:

![image](https://user-images.githubusercontent.com/103518137/179993954-8a827b0a-b00d-4e3c-8e80-5c54ffb9df24.png)

 However, I used the purple custom icon "011PowerBook" for the "Non-Fiction" folder and it just doesn't show properly on the file explorer panel anymore

![image](https://user-images.githubusercontent.com/103518137/179992605-30e13cb2-6e7b-456d-bf08-3af7e74618a3.png)

**Comment by GinoReiji** [comment]
I used [this icon pack](https://www.flaticon.com/packs/books-57) among many others and seems like most of them can't be displayed properly.

The icon I used in the example is this one:
![011-power book](https://user-images.githubusercontent.com/103518137/180111265-4aa423ff-5bf1-4270-9fbd-1621f58cb34f.svg)

**Comment by FlorianWoelki** [comment]
This issue should be fixed in version `1.3.2`. Thank you for reporting!
